### ISSUE TITLE
Exception when PaymentResponse contains metadata

### ISSUE THREAD

**Issue by lucwuyts** [Viincenttt/MollieApi#10]
The jsondeserializer throws an exception when the PaymentRespons contains a Metadata object.
This is property is defined as string 
To solve it, i made a class "Metadata" and defined the property as Metadata

public class Metadata
    {
        public string Order_Id { get; set; }
    }

This seems to work ok now

**Comment by Viincenttt** [comment]
Hi lucwuyts, 

Could you show me some code to reproduce this issue? I have tried the following code which works fine on my end: 
```c#
// If: We create a payment with meta data
            string json = "{\"employees\":[\r\n    {\"firstName\":\"John\", \"lastName\":\"Doe\"},\r\n    {\"firstName\":\"Anna\", \"lastName\":\"Smith\"},\r\n    {\"firstName\":\"Peter\", \"lastName\":\"Jones\"}\r\n]}";
            PaymentRequest paymentRequest = new PaymentRequest() {
                Amount = 100,
                Description = "Description",
                RedirectUrl = this.DefaultRedirectUrl,
                Metadata = json
            };

            // When: We send the payment request to Mollie
            PaymentResponse result = this._mollieClient.CreatePaymentAsync(paymentRequest).Result;

            // Then: Make sure we get the same json result as metadata
            Assert.AreEqual(json, result.Metadata);
```

**Comment by lucwuyts** [comment]
i'm only retrieving the paymentlist
ListResponse<PaymentResponse> paymentList = await mollie.GetPaymentListAsync();

This is response.Content returnd in the ProcessHttpResponseMessage<T> method

{"totalCount":20,"offset":0,"count":1,"data":[{"id":"tr_CQvM59jqpH","mode":"live","createdDatetime":"2016-08-04T15:01:04.0Z","status":"paidout","paidDatetime":"2016-08-04T15:03:34.0Z","amount":"24.00","amountRefunded":"0.00","amountRemaining":"49.00","description":"KATR!NARUN  0 - 4.40","method":"mistercash","metadata":{"order_id":"4.40"},"details":{"cardFingerprint":"rPJya8drqpn4CtTrfSaDbVwj","cardNumber":"8009"},"profileId":"pfl_WW6sEcrgGs","links":{"webhookUrl":"http://www.katrinahof.be/oc/cli/notify.php?transaction_id=1470322863","redirectUrl":"http://www.katrinahof.be/oc/cli/notify.php?transaction_id=1470322863&output=customer"}}],"links":{"first":"https://api.mollie.nl/v1/payments?count=1&offset=0","previous":null,"next":"https://api.mollie.nl/v1/payments?count=1&offset=1","last":"https://api.mollie.nl/v1/payments?count=1&offset=19"}}

**Comment by Viincenttt** [comment]
Hi lucwuyts,

I managed to reproduce your bug report and have committed a fix. I will release a new version and update the NuGet package as soon as possible.

Kind regards,
Vincent

**Comment by lucwuyts** [comment]
Ok, thanks!
