### ISSUE TITLE
Payment status API V2

### ISSUE THREAD

**Issue by renklapper** [Viincenttt/MollieApi#110]
Hello,

In the Mollie documentation for [v2 version of the API](https://docs.mollie.com/payments/status-changes), it lists the following statuses for the payment status:
* open
* canceled
* pending
* authorized
* expired
* failed
* paid

Although, the [PaymentStatus enum](https://github.com/Viincenttt/MollieApi/blob/08f7a64ccf63c249212357d40855a38b2a2d17db/Mollie.Api/Models/Payment/PaymentStatus.cs) available on the PaymentResponse has what seems to be the statuses from API v1:
* Open,
 * Canceled,
* Pending,
* Paid,
* PaidOut,
* Refunded,
* Expired,
* Failed,
* Charged_Back

Mollie documentation also states: "In the v1 API, there were statuses for when payments were refunded, charged back, or paid out (settled). These statuses have been removed in v2. You can get the same information from other properties on the Payment object."

**Comment by Viincentttt** [comment]
Hi @renklapper ,

Good find! I'll take a look at this! 

Kind regards,
Vincent

**Comment by Viincenttt** [comment]
Thanks, I merged your pull request into the development branch. I will update once this is live.

**Comment by renklapper** [comment]
@Viincenttt: Do you know when these changes will be released?

**Comment by Viincenttt** [comment]
Live in 2.0.5.0
