### ISSUE TITLE
Find a more elegant way to handle new enum values

### ISSUE THREAD

**Issue by Viincenttt** [Viincenttt/MollieApi#113]
When a new enum value is introduced by Mollie and is returned in an API call, the library throws a JsonSerializationException. This has caused many issues so far, for example:
- Issue #108 
- Issue #107 
- Issue #75 
- Issue #53 

Right now the Mollie API has to be updated whenever a new enum value is introduced. This is not okay, because that means all library consumers have to update their application aswell. 

I think the best solution is to create a custom JsonConverter for enums, that will serialize to a "Unknown" value whenever it can't parse the json value to an enum.

**Comment by JonathanJTOAna** [comment]
Do you plan to handle this issue? How can we help?

**Comment by cteiosanu** [comment]
@Viincenttt 
Is it possible to just leave enums as strings and convert the existing enum values into classes with public consts (to have a middle ground between backward and future compatibility) ?

**Comment by Viincenttt** [comment]
This issue is now fixed in version 2.1.0.0. Take a look at the release notes for a full list of fixes and changes:
https://github.com/Viincenttt/MollieApi/releases/tag/2.1.0.0

We are now using constant string values everywhere instead of enums. Although this is less intuitive then enums, it does mean that the API client won't break every time a new enum value is introduced, so it's a good trade off in my opinion.
