### ISSUE TITLE
GetPaymentAsync Result return exception when payment Canceled

### ISSUE THREAD

**Issue by mighty-nyaina** [Viincenttt/MollieApi#114]
Hi,
it's seems that there is an exception on GetPaymentAsync Result when status is different of Paid.
I need to know if the status is paid or canceled or failed in order to register each log of payments with their corresponding status in database.
Note that I am on testmode.  

Thanks

**Comment by mighty-nyaina** [comment]
Yes here the exceptions that appears only when status is different of paid


Exception interne 1 :
JsonSerializationException : Error converting value "unknown_reason" to type 'System.Nullable`1[Mollie.Api.Models.Payment.Response.CreditCardFailureReason]'. Path 'details.failureReason', line 1, position 704.

Exception interne 2 :
ArgumentException : Requested value 'unknown_reason' was not found.

> Any details of the exception?

**Comment by lgoudriaan** [comment]
Ah I see, this issue is resolved in the latest version: https://github.com/Viincenttt/MollieApi/releases/tag/2.0.4.0

**Comment by mighty-nyaina** [comment]
> Ah I see, this issue is resolved in the latest version: https://github.com/Viincenttt/MollieApi/releases/tag/2.0.4.0

So I upgraded the version of the package now it can not make any payment request without any error, it's just load infinitely.

**Comment by lgoudriaan** [comment]
Sounds like an async deadlock, how do you call the method?

**Comment by mighty-nyaina** [comment]
> Sounds like an async deadlock, how do you call the method?

It's also load infinitely when I try to get payment response like this : 

IPaymentClient paymentClient = new PaymentClient("molliApiKey");
PaymentResponse result = paymentClien.GetPaymentAsync("paymentId").Result;

Thanks

**Comment by lgoudriaan** [comment]
You should call the method like:
PaymentResponse result = **await** paymentClient.GetPaymentAsync("paymentId");

**Comment by Viincenttt** [comment]
That's correct. Take a look at the following link for more information:
[https://blog.stephencleary.com/2012/07/dont-block-on-async-code.html](https://blog.stephencleary.com/2012/07/dont-block-on-async-code.html)

**Comment by mighty-nyaina** [comment]
Sorry for the late response, the result is the same as if we use
PaymentResponse result = paymentClient.GetPaymentAsync ("payId"). Result;

Nothing happens, it's like it can not get the result back.
Here is my source code

```
public static async Task GetPaymentAsync()
        {
            IPaymentClient paymentClient = new PaymentClient(ApplicationSettings.MollieApiKey);
            PaymentResponse result = await paymentClient.GetPaymentAsync("paimentId"); //nothing happens after this lines
            
            if (result.Status == PaymentStatus.Canceled)
            {
                   //some stuffs
            }
        }
```

**Comment by lgoudriaan** [comment]
How do you call `GetPaymentAsync()`?

**Comment by mighty-nyaina** [comment]
> How do you call `GetPaymentAsync()`?

```
public static async Task GetPaymentAsync()
{
       IPaymentClient paymentClient = new PaymentClient(ApplicationSettings.MollieApiKey);
       PaymentResponse result = await paymentClient.GetPaymentAsync("paimentId"); //nothing happens after this lines
            
       if (result.Status == PaymentStatus.Canceled)
       {
              //some stuffs
        }
}
```

**Comment by lgoudriaan** [comment]
I mean your own `public static async Task GetPaymentAsync()` function.

`await YourClassname.GetPaymentAsync()` or `YourClassname.GetPaymentAsync().Result`

You should use async all the way up

**Comment by mighty-nyaina** [comment]
> await YourClassname.GetPaymentAsync()

I use
await YourClassname.GetPaymentAsync()

**Comment by lgoudriaan** [comment]
You have to make sure the whole call stack is async. See @Viincenttt comment here https://github.com/Viincenttt/MollieApi/issues/114#issuecomment-472533057
