### ISSUE TITLE
Customer payments endpoint

### ISSUE THREAD

**Issue by Zinshis** [Viincenttt/MollieApi#118]
The code that lists the customer payments is pointing to an incorrect endpoint.
`MollieApi/Mollie.Api/Client/PaymentClient.cs > GetCustomerPaymentListAsync (line 60)`

The function uses the "payments/{customerId}" endpoint while the official [API reference](https://docs.mollie.com/reference/v2/customers-api/list-customer-payments#) mentions to use the "customers/{customerId}/payments" endpoint.

**Comment by Viincenttt** [comment]
Hi @Zinshis 

Thanks for reporting this, I've fixed it on the development branch and will release soon. 

Kind regards,
Vincent

**Comment by Viincenttt** [comment]
Live in 2.0.5.0
