### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by furkandeveloper** [Viincenttt/MollieApi#123]
Hi,

I'm developing an application on .net core and I got this error when I integrated the create Payment part of your application into my application. I would appreciate if you could help.

MollieApiException: Unprocessable Entity - Non-existent body parameter "$id" for this API call. Did you mean: "method"?

**Comment by Viincenttt** [comment]
Which method are you calling when this error occurs?

**Comment by Viincenttt** [comment]
Closed because of no further info
