### ISSUE TITLE
Platform issue

### ISSUE THREAD

**Issue by VincentVanHulst** [Viincenttt/MollieApi#128]
Hi,

We are using the MollieAPI in our test environments now and it works perfect; but somehow on several servers (windows 2008 R2 with framework 4.7 installed), the API throws an exception as soon as it is used: 

Method not found: 'Void Mollie.Api.Client.PaymentClient..ctor(System.String, System.Net.Http.HttpClient)'.

Is there a minimum requirement that i am missing? The api is used on an asp.net webforms application.

**Comment by Viincenttt** [comment]
Hi there fellow Vincent! 

That is very strange! Perhaps you already found this yourself, but have you tried any of the solutions in this stackoverflow post? 
https://stackoverflow.com/questions/7578583/method-not-found-on-runtime 

If it still doesn't work, can you send me a small demo project that demonstrates the problem? 

Kind regards,
Vincent

**Comment by VincentVanHulst** [comment]
Hi Vincent,

 

Wat mij betreft kan het ook in het NL, maar weet niet of je voor de dossier-vorming op github liever in EN communiceert. (Laat maar even weten)

Ik vermoed inderdaad dat issue te maken heeft met wat jij doorstuurde maar dan begrijp ik nog niet zo goed waarom het op de ene omgeving wel werkt en op de andere niet. Recente windows server machines met de laatste .net framework versions doen het wel ok, oudere windows 2008 server versies werken dan weer niet. De IIS/webapp configuraties zijn exact dezelfde; dus in de bin-folder zitten dezelfde libraries. 

 

Heeft de API een specifieke system.net.http dll nodig?

 

Met vriendelijke groet,
Vincent van Hulst – MVA ICT

M: +31-6-41949320
E: vincent.vanhulst@mva-ict.nl <mailto:vincent.vanhulst@mva-ict.nl> 
W: www.mva-ict.nl 



 

Van: Vincent Kok <notifications@github.com> 
Verzonden: donderdag 23 mei 2019 18:43
Aan: Viincenttt/MollieApi <MollieApi@noreply.github.com>
CC: VincentVanHulst <vincent.vanhulst@mva-ict.nl>; Author <author@noreply.github.com>
Onderwerp: Re: [Viincenttt/MollieApi] Platform issue (#128)

 

Hi there fellow Vincent!

That is very strange! Perhaps you already found this yourself, but have you tried any of the solutions in this stackoverflow post?
https://stackoverflow.com/questions/7578583/method-not-found-on-runtime

If it still doesn't work, can you send me a small demo project that demonstrates the problem?

Kind regards,
Vincent

**Comment by VincentVanHulst** [comment]
Hi,

 

Nog een andere vraag (weet niet of ik die bij jou moet neerleggen of direct bij mollie):

 

Hoe kan ik een betaalreferentie meegeven aan een payment? Het is van belang dat een door ons systeem gegenereerde referentie (of gestructureerde mededeling in België), meegegeven wordt aan de betaling zodat bij het verwerken van de bankbestanden de mutaties automatisch gematched kunnen worden.

 

Alvast bedankt!

 

Met vriendelijke groet,
Vincent van Hulst – MVA ICT

M: +31-6-41949320
E: vincent.vanhulst@mva-ict.nl <mailto:vincent.vanhulst@mva-ict.nl> 
W: www.mva-ict.nl 



 

Van: Vincent Kok <notifications@github.com> 
Verzonden: donderdag 23 mei 2019 18:43
Aan: Viincenttt/MollieApi <MollieApi@noreply.github.com>
CC: VincentVanHulst <vincent.vanhulst@mva-ict.nl>; Author <author@noreply.github.com>
Onderwerp: Re: [Viincenttt/MollieApi] Platform issue (#128)

 

Hi there fellow Vincent!

That is very strange! Perhaps you already found this yourself, but have you tried any of the solutions in this stackoverflow post?
https://stackoverflow.com/questions/7578583/method-not-found-on-runtime

If it still doesn't work, can you send me a small demo project that demonstrates the problem?

Kind regards,
Vincent

**Comment by Viincenttt** [comment]
Hi Vincent,

I prefer english so other people that do not speak dutch can also read the conversation. 

Another possible cause for this problem could be if different versions of the Mollie.Api library are used within the same solution. Make sure that every project that references the Mollie.Api.dll uses the same version. 

Another important thing to note is that the NuGet package contains two .dll files: One .dll for .NET 4.5 and another one for netstandard. It could be that this is causing the issue, but I can't say I've heard about it before. You could try to pull the latest version of my library and compiling it yourself. Then you can you use that .dll. Please let me know if that resolves the issue. 

Regarding the second question: You can use the MetaData property on a PaymentRequest to add your own custom data. Take a look at the documentation on how to do this:
https://github.com/Viincenttt/MollieApi#setting-metadata

**Comment by VincentVanHulst** [comment]
Hi Vincent,

 

I’ve downloaded your package, removed the netstandard references and pointed the System.Net.Http reference to the version we use; that solved the problem. Seemed a version conflict somehow.

Thnx

 

Met vriendelijke groet,
Vincent van Hulst – MVA ICT

M: +31-6-41949320
E: vincent.vanhulst@mva-ict.nl <mailto:vincent.vanhulst@mva-ict.nl> 
W: www.mva-ict.nl 



 

Van: Vincent Kok <notifications@github.com> 
Verzonden: donderdag 23 mei 2019 22:34
Aan: Viincenttt/MollieApi <MollieApi@noreply.github.com>
CC: VincentVanHulst <vincent.vanhulst@mva-ict.nl>; Author <author@noreply.github.com>
Onderwerp: Re: [Viincenttt/MollieApi] Platform issue (#128)

 

Hi Vincent,

I prefer english so other people that do not speak dutch can also read the conversation.

Another possible cause for this problem could be if different versions of the Mollie.Api library are used within the same solution. Make sure that every project that references the Mollie.Api.dll uses the same version.

Another important thing to note is that the NuGet package contains two .dll files: One .dll for .NET 4.5 and another one for netstandard. It could be that this is causing the issue, but I can't say I've heard about it before. You could try to pull the latest version of my library and compiling it yourself. Then you can you use that .dll. Please let me know if that resolves the issue.

Regarding the second question: You can use the MetaData property on a PaymentRequest to add your own custom data. Take a look at the documentation on how to do this:
https://github.com/Viincenttt/MollieApi#setting-metadata
