### ISSUE TITLE
Locale

### ISSUE THREAD

**Issue by SnowZA** [Viincenttt/MollieApi#13]
The Locale enum needs at least one extra value.

I tested on a PC with Location set to Netherlands, but language set to English (United Kingdom). 

I didn't specify a locale when creating the payment. The payment was created without any errors. However, when trying to retrieve that payment from the Mollie API, I get de-serialization errors. The Locale being returned is "uk", not "en" as expected.

Adding "UK" to the Locale enum solves the problem.

**Comment by Viincenttt** [comment]
Hi SnowZA,

Thank you for reporting this issue. I have asked Mollie support what the possible Locale values could be. I will keep you updated.

Kind regards,

**Comment by Viincenttt** [comment]
Mollie support has forwarded my ticket to their developers. Still awaiting their response.

**Comment by Viincenttt** [comment]
Hi SnowZA,

I have contacted Mollie again to see if they have an answer for this problem. I'm not sure if you are dutch, but their response was: 
"Ik heb hier helaas nog geen antwoord op. Er is een melding voor, maar ze (de developers) moeten nog even kijken hoe ze dit precies gaan aanpakken."

Kind regards,
Vincent

**Comment by SnowZA** [comment]
Hi

I'm not originally Dutch, but I do speak Dutch - I've lived here for 8 years now. 

From this reply, it looks to me like they haven't really thought it through properly themselves yet. Maybe it would be a good idea then to add the known missing value to the enum, and then revisit it later once the Mollie developers figure out what they want to do.

Regards
  Roderick

**Comment by Viincenttt** [comment]
Hi Snowza,

Unfortunatly Mollie doesn't reply to my ticket anymore. I have decided that using an enum for Locale's is too restrictive, because Mollie can't decide on what values to use. Therefore, I am now using a string for the Locale value. The presets, such as nl, en etc are still available in the static Locale class. 

This issue is fixed in version 1.3.6.

Kind regards,
Vincent
