### ISSUE TITLE
Your api

### ISSUE THREAD

**Issue by DehookBv** [Viincenttt/MollieApi#130]
Dear Vincent 
I'm not a developer, so I don't have a technical knowledge.
I want to buy a new e-commerce package, but this e-commerce package does not have the option of payment with the ideal.
I'm working with mollie. So I want to link this e-commerce package with mollie.
e-commerce package using asp.net,
I hesitate to buy this e-commerce site.
If I can't integrate with mollie, it won't work for me.
Can we use your api to pay mollie. I think we have an agreement with a software developer, you can give information about it.

**Comment by Viincenttt** [comment]
Hi DehookBv,

Maybe you can and maybe you can't. Impossible to tell without knowing more details about the e-commerce platform and technology behind it. I'd ask the software developer you intend to hire for this to research the possibilities. Feel free to open a new ticket if you or the software developer have technical questions regarding this library. 

Kind regards,
Vincent
