### ISSUE TITLE
Is there any way in page  list of payment to only show the last payment

### ISSUE THREAD

**Issue by mpiri** [Viincenttt/MollieApi#135]
Hi,
I want customers to be able to pay without an account. The customers should immediately be redirected to the check-out page without seeing the entire list of payments.
Is this possible?
regards.

**Comment by Viincenttt** [comment]
Hi mpiri,

I am not sure what you mean. Customers do not need a Mollie account to pay anything. If you want to pre-select a payment method for the customer, this is also possible if you add a payment method to the `PaymentRequest` object. 

Kind regards,
Vincent

**Comment by mpiri** [comment]
Hi,
I don't mean Mollie account. I want customers to be able to pay without seeing the entire list of payments.  Customers can save a new payment on views->Payment-> create.cshtml.   After that the customer is redirected to the Index.cshtml (views->Payment->Index.cshtml).  It shows a payment list of all transactions including payment status. I want that customers only see the last actual payment instead of all payments.

How can I make this happen?

regards,

**Comment by Viincenttt** [comment]
Hi,

I think you are referring to the example project. The example project is for demonstration purposes only. It's not meant to be used by your customers. To create payments, use the API in your own C# project. Take a look at the documentation in the readme.md or get inspiration from the example project. 

Kind regards,
Vincent
