### ISSUE TITLE
Can you create a payment with a Test API-Key?

### ISSUE THREAD

**Issue by maurictg** [Viincenttt/MollieApi#136]
Hi Vincentt,
Can you tell me what will and what won't work with a test api-key?

Kind regards,
maurict

**Comment by Viincenttt** [comment]
Hi maurictg,

You can create test payments. I think you should probably ask this question to the Mollie helpdesk though. I am not affiliated with Mollie. 

Kind regards,
Vincent

**Comment by maurictg** [comment]
Thanks, it is working now.
You first have to enable a payment method in https://www.mollie.com/dashboard/settings/profiles
before the test api key works.
