### ISSUE TITLE
Metadata in RefundRequest

### ISSUE THREAD

**Issue by StefaanHlsl** [Viincenttt/MollieApi#137]
Is it possible to provide metadata in the RefundRequest?

Thx
Stefaan

**Comment by Viincenttt** [comment]
Hi Stefaan,

Mollie supports it, but the library does not. See the mollie documentation:
https://docs.mollie.com/reference/v2/refunds-api/create-refund

It should be trivial to add. If you create a pull request for it I can merge it for you. 

Kind regards,
Vincent

**Comment by Viincenttt** [comment]
This PR has been merged
