### ISSUE TITLE
Request QR code for bancontact

### ISSUE THREAD

**Issue by cvercammen** [Viincenttt/MollieApi#147]
Hi, 

Is it possible to request a QR code by adding "include:details.qrCode" to the API query? 
Like this : https://api.mollie.com/v2/payments?include=details.qrCode 

https://docs.mollie.com/reference/v2/payments-api/create-payment#qr-codes 

I can't figure it out.
Thanks in advance!

Best regards, 

Chris

**Comment by Viincenttt** [comment]
Hi cvercammen,

Right now the API library does not support this options. If you want, you can create a PR to support it. 

Kind regards,
Vincent

**Comment by Viincenttt** [comment]
This feature is now supported in version 2.1.0.0. Take a look at the release notes for a full list of fixes and changes:
https://github.com/Viincenttt/MollieApi/releases/tag/2.1.0.0
