### ISSUE TITLE
Get the status: WaitingForActivation during making the payment

### ISSUE THREAD

**Issue by Ghits-nl** [Viincenttt/MollieApi#149]
Hi,
I am getting the "id: 240 status = WaitingForActivation" during making a payment. If I doe de same and with the same ApiKey on another example application iet works fine. Anyone Any idea?

**Comment by Viincenttt** [comment]
Did you manage to figure this one out? I haven't seen this error before

**Comment by Viincenttt** [comment]
Closing until more information is available
