### ISSUE TITLE
Newtonsoft.Json version

### ISSUE THREAD

**Issue by lxalln** [Viincenttt/MollieApi#151]
Is there a particular need for this library to use such a high version of Json.NET? We deploy to Azure functions which are limited to 11.0.2 (and enforce that with their own special version of dll hell).

12.x.x brings breaking changes for parts of the library we use. I am unable to use this library in production on Azure functions.

I appreciate that the blame for this rests solely on the shoulders of the Azure Functions developers, however, I am currently forced to use version 2.0.2 of this library, before you upped the Json.NET version.

**Comment by Viincenttt** [comment]
Hi, 

I'm not sure if it is necessery, however, I feel it is important to keep packages up to date whereever possible. This is because new packages can include important bugfixes or security updates. I consider keeping NuGet packages up-to-date a best practice. 

Perhaps you could try to fork the library and use a lower version of Json.NET untill Azure functions fixes their issues? 

Kind regards,
Vincent

**Comment by lxalln** [comment]
I agree that it is important to keep packages up to date, I just don't agree that it is the responsibility of a library to enforce that on project developers.




Project developers will test versions of JSON.net and use the latest one that works for them. By including this library, you forcing the latest version of JSON.net on developers.




I am currently using an older version of this library (before the dependency was upped), which means I am now missing out on any security or bug fixes you put out.




Even if I fork the project, it'll almost certainly fall out of sync and then the same problem exists.




It is of course your decision, but I am disappointed.




On Fri, Nov 22, 2019 at 7:10 PM +0000, "Vincent Kok" <notifications@github.com> wrote:












Closed #151.

**Comment by Viincenttt** [comment]
Hi lxalln,

Thanks for your feedback. Have you tried the following solution:
https://stackoverflow.com/questions/50286990/error-nu1605-detected-package-downgrade/50323131

I just tried on it a empty console application and I was able to add my library (which uses Newtonsoft 12.0.3) and also reference newtonsoft 11.0.2, which is the version you wanted to use. Please let me know if this resolves the issue. 

Kind regards,
Vincent

**Comment by lxalln** [comment]
@Viincenttt unfortunately this isn't about being able to build the project, that works fine (using the above). It's that Azure functions force a version of JSON.net.

And because there are breaking changes (in what we use) between 11.0.2 and 12.0.3, this can't be 'faked'. Missing method exceptions get thrown.

I believe my next course of action will be to fork this library and lower the version of JSON.net
