### ISSUE TITLE
Need for standard ASP.NET / Console sample

### ISSUE THREAD

**Issue by marcverkade** [Viincenttt/MollieApi#159]
I was struggling to get the simple console sample of the Mollie API V2 working. Finally got it working:

```
using System;
using Mollie.Api.Client;
using Mollie.Api.Models.List;
using Mollie.Api.Models.Payment.Request;
using Mollie.Api.Models.Payment.Response;
using Mollie.Api.Models.PaymentMethod;
using Mollie.Api.Models;
using System.Diagnostics;

namespace Mollie.SimpleExample {
    class Program {
        static void Main(string[] args) {

            // MLV20191126 Put you test Mollie API key here
            string apiKey = "<<YOUR TEST API KEY HERE>>";

            PaymentClient paymentClient = new PaymentClient(apiKey);
            PaymentMethodClient paymentMethodClient = new PaymentMethodClient(apiKey);

            OutputAndWait("Press any key to create a new payment");
            OutputNewPayment(paymentClient);
            OutputAndWait("Press any key to retrieve a list of payments");
            OutputPaymentList(paymentClient);
            OutputAndWait("Press any key to retrieve a list of payment methods");
            OutputPaymentMethods(paymentMethodClient);
            OutputAndWait("Example completed");
        }

        static void OutputNewPayment(PaymentClient paymentClient) {
            Console.WriteLine("Creating a payment");
            PaymentRequest paymentRequest = new PaymentRequest() {
                Description = "Test payment of the example project",
                RedirectUrl = "http://google.com"
            };

            // MLV20191126 Set the new payment amount for API V2
            Amount oAmount = new Amount(Currency.EUR, "100.00");
            paymentRequest.Amount = oAmount;


            PaymentResponse paymentResponse = paymentClient.CreatePaymentAsync(paymentRequest).Result;
            Console.WriteLine("Payment created");
            Console.WriteLine("");

            // MLV20191126 Changed .PaymentUrl to .Checkout for API V2
            Console.WriteLine($"Payment can be paid on the following URL: {paymentResponse.Links.Checkout}");

            // MLV20191126 Open the payment URL
            Process.Start(paymentResponse.Links.Checkout.Href);

        }

        static void OutputPaymentList(PaymentClient paymentClient) {
            Console.WriteLine("Outputting the first 5 payments");
            // MLV20191126 Changed first parameter of GetPaymentListAsync() to null for API V2
            ListResponse<PaymentResponse> paymentList = paymentClient.GetPaymentListAsync(null, 5).Result;
            foreach (PaymentResponse paymentResponse in paymentList.Items) {
                Console.WriteLine($"Payment Id: { paymentResponse.Id } - Payment method: { paymentResponse.Method }");
            }
        }

        static void OutputPaymentMethods(PaymentMethodClient paymentMethodClient) {
            Console.WriteLine("Ouputting all payment methods");
            // MLV20191126 Deleted parameters of GetPaymentMethodListAsync() for API V2
            ListResponse<PaymentMethodResponse> paymentMethodList = paymentMethodClient.GetPaymentMethodListAsync().Result;
            foreach (PaymentMethodResponse paymentMethodResponse in paymentMethodList.Items) {
                Console.WriteLine($"Payment method description: { paymentMethodResponse.Description }");
            }
        }

        static void OutputAndWait(string output) {
            Console.WriteLine(output);
            Console.ReadKey();
        }
    }
}
```

**Comment by marcverkade** [comment]
This is the old 'simple example'... Can this be changed to use API V2?

using System;
using Mollie.Api.Client;
using Mollie.Api.Models.List;
using Mollie.Api.Models.Payment.Request;
using Mollie.Api.Models.Payment.Response;
using Mollie.Api.Models.PaymentMethod;
using Mollie.Api.Models;

namespace Mollie.SimpleExample {
    class Program {
        static void Main(string[] args) {
            string apiKey = "test_99ESjg2Tm858mEC4FbLkL3fbKGgRAH";
            PaymentClient paymentClient = new PaymentClient(apiKey);
            PaymentMethodClient paymentMethodClient = new PaymentMethodClient(apiKey);

            OutputAndWait("Press any key to create a new payment");
            OutputNewPayment(paymentClient);
            OutputAndWait("Press any key to retrieve a list of payments");
            OutputPaymentList(paymentClient);
            OutputAndWait("Press any key to retrieve a list of payment methods");
            OutputPaymentMethods(paymentMethodClient);
            OutputAndWait("Example completed");
        }

        static void OutputNewPayment(PaymentClient paymentClient) {
            Console.WriteLine("Creating a payment");
            PaymentRequest paymentRequest = new PaymentRequest() {
                Description = "Test payment of the example project",
                RedirectUrl = "http://google.com"
            };

            // MLV20191126 Set the new payment amount
            Amount oAmount = new Amount(Currency.EUR, "100.00");
            paymentRequest.Amount = oAmount;


            PaymentResponse paymentResponse = paymentClient.CreatePaymentAsync(paymentRequest).Result;
            Console.WriteLine("Payment created");
            Console.WriteLine("");

            // MLV20191126 Changed .PaymentUrl to .Checkout
            Console.WriteLine($"Payment can be paid on the following URL: {paymentResponse.Links.Checkout}");
        }

        static void OutputPaymentList(PaymentClient paymentClient) {
            Console.WriteLine("Outputting the first 2 payments");
            ListResponse<PaymentResponse> paymentList = paymentClient.GetPaymentListAsync(0, 2).Result;
            foreach (PaymentResponse paymentResponse in paymentList.Data) {
                Console.WriteLine($"Payment Id: { paymentResponse.Id } - Payment method: { paymentResponse.Method }");
            }
        }

        static void OutputPaymentMethods(PaymentMethodClient paymentMethodClient) {
            Console.WriteLine("Ouputting all payment methods");
            ListResponse<PaymentMethodResponse> paymentMethodList = paymentMethodClient.GetPaymentMethodListAsync(0, 100).Result;
            foreach (PaymentMethodResponse paymentMethodResponse in paymentMethodList.Data) {
                Console.WriteLine($"Payment method description: { paymentMethodResponse.Description }");
            }
        }

        static void OutputAndWait(string output) {
            Console.WriteLine(output);
            Console.ReadKey();
        }
    }
}

**Comment by Viincenttt** [comment]
Hi Marc,

The Mollie API v2 doesn't have a console application example. The only included example project is the Mollie.WebApplicationCoreExample project, which can be found here: https://github.com/Viincenttt/MollieApi/tree/development/Mollie.WebApplicationCoreExample

Kind regards,
Vincent
