### ISSUE TITLE
I need a little bit of help

### ISSUE THREAD

**Issue by aartatimago** [Viincenttt/MollieApi#16]
Hello,
Is there anybody who can help me a little bit further.

I've been succesfull in making a "paymentrequest" to mollie and I also can get the "paymentresponse".
`PaymentResponse result = this._mollieClient.GetPaymentAsync(psPaymentId).Result;`

But I also want to receive the "IdealPaymentResponse" and "IdealPaymentResponseDetails".
How can I get these responses?

Thanks for any help.

Aart

**Comment by Viincenttt** [comment]
Hi Aartatimago,

If you know the type of payment you can cast the PaymentResponse to the a payment specific PaymentResponse. For example: 
`IdealPaymentResponse result = this._mollieClient.GetPaymentAsync(psPaymentId).Result as IdealPaymentResponse;`

**Comment by aartatimago** [comment]
Hallo Vincent,

Thanks for your quick answer.
It turns out that I was not that far from the right solution.

Thank you again.

With kind regards,
Aart
