### ISSUE TITLE
Error parsing CreditCardFailureReason values (authentication & authentication_failed)

### ISSUE THREAD

**Issue by nowoffline** [Viincenttt/MollieApi#160]
It seems Mollie has added two possible failure reasons for credit cards, which break the api when trying to convert those values to the CreditCardFailureReason enum.

The values which are breaking the code:
```
authentication
authentication_failed
```

For completeness:
```
Newtonsoft.Json.JsonSerializationException: Error converting value "authentication" to type 'System.Nullable`1[Mollie.Api.Models.Payment.Response.CreditCardFailureReason]'. Path 'details.failureReason', line 1, position 833. ---> System.ArgumentException: Requested value 'authentication' was not found.

Newtonsoft.Json.JsonSerializationException: Error converting value "authentication_failed" to type 'System.Nullable`1[Mollie.Api.Models.Payment.Response.CreditCardFailureReason]'. Path 'details.failureReason', line 1, position 840. ---> System.ArgumentException: Requested value 'authentication_failed' was not found.
```

**Comment by Viincenttt** [comment]
Hi,

Is `authentication` a value that can be returned from the API? I can only find `authentication_failed` in the documentation: https://docs.mollie.com/reference/v2/payments-api/get-payment

Kind regards,
Vincent

**Comment by nowoffline** [comment]
Hi Vincent,

Maybe? That's why I included both exceptions that have occurred recently for a couple of payments. For example, a specific payment that was done by a user first returned the failure reason `authentication` and after a week it changed to `authentication_failed`.

Of course, it could be Mollie simply renamed the value in the past week.

**Comment by Viincenttt** [comment]
I added support for the `authentication_failed` enum in Mollie API 2.0.7.1
