### ISSUE TITLE
Using the Mollie Api for Xamarin Forms PCL

### ISSUE THREAD

**Issue by Fatihpk** [Viincenttt/MollieApi#161]
Hi There is it possible to use the Moillie Api for Xamarin Forms PCL with Android + iOS?

**Comment by Viincenttt** [comment]
Hi Fatihpk,

I haven't tried this myself, but the library is compatible with .NET standard 1.2. I'm not really up to date with Xamarin Forms PCL and which .NET version is compatible with that.

**Comment by Fatihpk** [comment]
It has to contain a wrapper for iOS and Android @Viincenttt
