### ISSUE TITLE
Deadlock

### ISSUE THREAD

**Issue by Erik-van-Loenen** [Viincenttt/MollieApi#163]
I am using this tool for iDeal payment in my webshop. The only thing I use is the PaymentClient (CreatePaymentAsync and GetPaymentAsync) and both calls resulted in a deadlock.
I have fixed this, by changing the following 2 lines of code:

BaseMollieClient.cs:48> Added .ConfigureAwait(false)
BaseMollieClient.cs:57> Added .ConfigureAwait(false)

It probably should be added in more places, but this served my purpose

**Comment by aevitas** [comment]
Are you calling `.GetResult()` or `.Result` instead of using `await`? Adding `ConfigureAwait(false)` is good practice for a library such as this one, but its absence is not the root cause of the deadlock.

**Comment by Viincenttt** [comment]
As aevitas wrote, if you are using `.GetResult()` or `.Result` you are risking deadlocks. However, I did add the `ConfigureAwait(false)` statement to several places where it was missing.

**Comment by Viincenttt** [comment]
This is now solved in version 2.0.7.2
