### ISSUE TITLE
OrganizationName missing in OrderAddressDetails?

### ISSUE THREAD

**Issue by dam3210** [Viincenttt/MollieApi#166]
Hi,

First of all, I'd like to thank you for this great library, super nice to use.

I noticed the "OrganizationName" is missing in "OrderAddressDetails". Is this true, or am I doing something wrong?

**Comment by Viincenttt** [comment]
Hi dam3210,

You aren't doing anything wrong. The property is missing. If you create a PR and add the property I will merge it. Or you can wait untill I have time to implement it :)

Kind regards,
Vincent

**Comment by Viincenttt** [comment]
This is now solved in version 2.0.7.2
