### ISSUE TITLE
amex-intra-eea is a new CreditCardFeeRegion

### ISSUE THREAD

**Issue by Bookzo** [Viincenttt/MollieApi#167]
Enum value should be added, now it gives an error:
Error converting value "amex-intra-eea" to type 'System.Nullable`1[Mollie.Api.Models.Payment.Response.CreditCardFeeRegion]'. Path 'details.feeRegion', line 1, position 1042. Requested value 'amex-intra-eea' was not found.

**Comment by Viincenttt** [comment]
Hi Bookzo,

That's strange. That value isn't listed in the Mollie documentation. I'll see if I can convert the `CreditCardFeeRegion` enum to a string, since Mollie seems to add values quite frequently. 

Kind regards,
Vincent

**Comment by Viincenttt** [comment]
This is now solved in version 2.0.7.2

**Comment by Bookzo** [comment]
Thanks!
