### ISSUE TITLE
Some SSl/TLS issue perhaps

### ISSUE THREAD

**Issue by trouble2** [Viincenttt/MollieApi#170]
Hi, we're trying to use the dll in a project and at some point I get:

System.AggregateException: One or more errors occurred. ---> System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: The underlying connection was closed: An unexpected error occurred on a receive. ---> System.ComponentModel.Win32Exception: The client and server cannot communicate, because they do not possess a common algorithm at System.Net.SSPIWrapper.AcquireCredentialsHandle(SSPIInterface SecModule, String package, CredentialUse intent, SecureCredential scc) at System.Net.Security.SecureChannel.AcquireCredentialsHandle(CredentialUse credUsage, SecureCredential& secureCredential) at System.Net.Security.SecureChannel.AcquireClientCredentials(Byte[]& thumbPrint) at System.Net.Security.SecureChannel.GenerateToken(Byte[] input, Int32 offset, Int32 count, Byte[]& output) at System.Net.Security.SecureChannel.NextMessage(Byte[] incoming, Int32 offset, Int32 count) at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest) at System.Net.Security.SslState.ForceAuthentication(Boolean receiveFirst, Byte[] buffer, AsyncProtocolRequest asyncRequest) at System.Net.Security.SslState.ProcessAuthentication(LazyAsyncResult lazyResult) at System.Net.TlsStream.CallProcessAuthentication(Object state) at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx) at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx) at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state) at System.Net.TlsStream.ProcessAuthentication(LazyAsyncResult result) at System.Net.TlsStream.BeginWrite(Byte[] buffer, Int32 offset, Int32 size, AsyncCallback asyncCallback, Object asyncState) at System.Net.TlsStream.UnsafeBeginWrite(Byte[] buffer, Int32 offset, Int32 size, AsyncCallback asyncCallback, Object asyncState) at System.Net.PooledStream.UnsafeBeginWrite(Byte[] buffer, Int32 offset, Int32 size, AsyncCallback callback, Object state) at System.Net.ConnectStream.WriteHeaders(Boolean async) --- End of inner exception stack trace --- at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult) at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar) --- End of inner exception stack trace --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Mollie.Api.Client.BaseMollieClient.d__5`1.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Mollie.Api.Client.BaseMollieClient.d__7`1.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Mollie.Api.Client.PaymentClient.d__2.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at

Can you tell me what I can do?

**Comment by trouble2** [comment]
I think this can happen if both servers use a different tls version.
For example our server only accepts TLS 1.2, and Mollie returns with TLS 1.0 or 1.1

**Comment by Viincenttt** [comment]
Hi trouble2,

If you do a Google search for the error `The client and server cannot communicate, because they do not possess a common algorithm`, you'll find that this is indeed a TLS protocol issue. Since it is not a issue that is related with the Mollie.Api library, I am closing this issue. 

Kind regards,
Vincent

**Comment by trouble2** [comment]
I understand it is a tls issue, but perhaps (i'm not sure) you should force tls 1.2 or something (if it is possible) because that is the standard? https://www.emerce.nl/achtergrond/tls-bijna-end-of-live-gevolgen-webapplicaties

**Comment by trouble2** [comment]
I had some other applications where I needed to be sure, and I had to do stuff like:

            ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12;			
            HttpWebRequest request = (HttpWebRequest)HttpWebRequest.Create(Url);

To enforce TLS12. So then you are sure the communication is done in TLS12
But I'm not sure how to adjust it in your code....to test if it might help

**Comment by Viincenttt** [comment]
Hi trouble2,

When you set the TLS protocol version like you are doing in the above code, you are forcing the entire application to use that version. This means that my library is forcing everyone to use TLS 1.2 for all the requests within their application. That does not sound like a choice I want to make for my library consumers. 

Kind regards,
Vincent
