### ISSUE TITLE
Request: Publish latest version to NuGet

### ISSUE THREAD

**Issue by sjonner** [Viincenttt/MollieApi#176]
Hi Vincent,

I see you're busy working on the project. Do you have an indication when a new version will be published to NuGet? There were a couple of merged pull request that we would like to use :)

Kind regards,
John

**Comment by Viincenttt** [comment]
Hi sjonner,

Good news, as of today I am jobless so I should have plenty of time to maintain this library and push new updates :P I'll release a new version this weekend. 

Kind regards,
Vincent

**Comment by Ziriax** [comment]
@Viincenttt I hope you find a new job soon.

**Comment by Viincenttt** [comment]
Thanks Ziriax, I'm sure I'll be fine :) 

I have just released a new version of the library: https://github.com/Viincenttt/MollieApi/releases/tag/2.0.7.3

Kind regards,
Vincent

**Comment by sjonner** [comment]
Thanks a bunch! Hope you find a good job soon!
