### ISSUE TITLE
MetaData property missing on OrderLineRequest

### ISSUE THREAD

**Issue by dam3210** [Viincenttt/MollieApi#179]
Hi,

I believe the property MetaData on OrderLineRequest and OrderLine is missing? Is that true?

Kind regards,
Damian

**Comment by Viincenttt** [comment]
Hi Damian,

Looks like it's missing. I guess it was added after we implemented the Order API. I'll see if I can add it soon. You are also welcome to create the PR yourself if you want to speed up the process :) It should not be difficult. 

Kind regards,
Vincent
