### ISSUE TITLE
Error in test mode with ValidateApiKeyIsOauthAccesstoken

### ISSUE THREAD

**Issue by jfmeyers** [Viincenttt/MollieApi#183]
Hi,

I have a _System.ArgumentException : 'The provided token isn't an oauth token.'_

I'm in **TEST mode** and my API key doesn't start with "access_" as it is written in your code.
It starts with "**test_**" (or "**live_**"in live mode) ex.: "test_n7kRCUWjhHd3kw..."

`protected void ValidateApiKeyIsOauthAccesstoken(bool isConstructor = false) {
            if (!this._apiKey.StartsWith("access_")) {
                if (isConstructor) {
                    throw new InvalidOperationException(
                        "The provided token isn't an oauth token. You have invoked the method with oauth parameters thus an oauth accesstoken is required.");
                }
                throw new ArgumentException("The provided token isn't an oauth token.");
            }
        }`

https://github.com/Viincenttt/MollieApi/blob/90f48b1c9db1e342b6fe3121bd2452755f72beaf/Mollie.Api/Client/BaseMollieClient.cs

Did I make a mistake?
If not, could you change your code? Or maybe I can make a Pull request?

Thank you

Jean-François

**Comment by Viincenttt** [comment]
Hi jfmeyers,

It's been a while since I've reviewed the code responsible for this, but if I remember correctly the testmode is only used/available when you are using OAuth tokens. If you want to test your application using a test API key (a token that starts with "test_xxxxx", you set the testmode to false and Mollie will automatically create it as a test payment. 

A quote from the Mollie documentation:
> If you are using organization access tokens or are creating an OAuth app, the testmode query string parameter is available. You must pass this as a parameter in the query string if you want to retrieve a payment that was created in test mode.

Let me know if you need any further help. 

Kind regards,
Vincent

**Comment by creativesuspects** [comment]
I just ran into the same issue. Setting testmode to false and using the token that starts with "test_" did indeed fix the problem. I reckon there are lots of developers that aren't using the organization access tokens or creating an OAUTH app and they will also be inclined to set the testmode to true. So this might be worth mentioning in the README?

**Comment by Viincenttt** [comment]
I agree with you, but I don't make the rules on how the Mollie API works. The way it currently works is that the testMode parameter only works for OAuth tokens. This library is only a wrapper around the Mollie API. Feedback on how the API works can be sent to Mollie.

**Comment by jfmeyers** [comment]
Hi Vincent,

Thank you for the quick response.
Indeed, I had not seen that TestMode was reserved for the "Organization" mode, or "OAuth App".
If I do not pass the parameter, everything works fine.

Thanks again

Jean-François

**Comment by Viincenttt** [comment]
Good to hear! :)
