### ISSUE TITLE
GetAllPaymentMethod Issue

### ISSUE THREAD

**Issue by BhoomiPansuriya** [Viincenttt/MollieApi#184]
Hi
I am getting "waiting for activation" when call GetAllPaymentMethod
below is my code block
 public ListResponse<PaymentMethodResponse> GetPaymentMethodList(string apiKey)
        {
            // ListResponse<IssuerResponse> issuerList = null;
            PaymentMethodClient _paymentMethodClient = new PaymentMethodClient(apiKey);
            var paymentMethodList =
                _paymentMethodClient.GetPaymentMethodListAsync().Result;        
            return paymentMethodList;
        }

**Comment by Viincenttt** [comment]
You are getting back the response "Waiting for activation" when you call that API method? In that case, your Mollie account is probably waiting for activation. 

By the way I notice that you aren't using async/await methods. I'd advice you to use async methods when using this library. You could run into issues later on if you don't.

**Comment by BhoomiPansuriya** [comment]
Thanks for your reply. The issue is solved.
