### ISSUE TITLE
"Details" node missing in PaymentResponse class

### ISSUE THREAD

**Issue by tustc79** [Viincenttt/MollieApi#186]
It seems that the Details element is missing in the PaymentResponse class. This contains information like IBAN and the name of the account holder. I only tested with Ideal payments, so maybe it is missing  in the Mollie response when using a different payment type (not tested).
Below the json when serializing PaymentResponse again.

_{
	"Details": {
		"ConsumerName": "T. TEST",
		"ConsumerAccount": "NL17RABO0xxxxxx",
		"ConsumerBic": "BUNQNL2A"
	},
	"Resource": "payment",
	"Id": "tr_qsDt7xxxxx",
	"Mode": 1,
	"CreatedAt": "2020-06-18T13:01:00+02:00",
	"Status": "Paid",
	"IsCancelable": false,
	"AuthorizedAt": null,
	"PaidAt": "2020-06-18T13:01:04+02:00",
	"CanceledAt": null,
	"ExpiresAt": null,
	"ExpiredAt": null,
	"FailedAt": null,
	"Amount": {
		"Currency": "EUR",
		"Value": "37.50"
	},
	"AmountRefunded": {
		"Currency": "EUR",
		"Value": "0.00"
	},
	"AmountRemaining": {
		"Currency": "EUR",
		"Value": "37.50"
	},
	"AmountCaptured": null,
	"Description": "Deelname Eventement",
	"RedirectUrl": "http://xxx.xxx.xxx.xxx/inschrijven/voltooid",
	"WebhookUrl": "http://xxx.xxx.xxx.xxx/inschrijven/mollie",
	"Method": "ideal",
	"Metadata": {
		"itemID": 20,
		"description": "Deelname Eventement"
	},
	"Locale": "en_NL",
	"CountryCode": "NL",
	"ProfileId": "pfl_hF73axxxx",
	"SettlementAmount": {
		"Currency": "EUR",
		"Value": "37.50"
	},
	"SettlementId": null,
	"CustomerId": null,
	"SequenceType": "oneoff",
	"MandateId": null,
	"SubscriptionId": null,
	"OrderId": null,
	"ApplicationFee": null,
	"_links": {
		"Self": {
			"Href": "https://api.mollie.com/v2/payments/tr_qsDt7v9VuJ",
			"Type": "application/hal+json"
		},
		"Checkout": null,
		"Refunds": null,
		"Chargebacks": null,
		"Settlement": null,
		"Documentation": {
			"Href": "https://docs.mollie.com/reference/v2/payments-api/get-payment",
			"Type": "text/html"
		},
		"Mandate": null,
		"Subscription": null,
		"Customer": null
	}
}_

**Comment by kryptonite** [comment]
Hitustc79,

According to the documentation you can access the specific payment properties by casting the response to the corresponding class.

> Keep in mind that some payment methods have specific payment detail values. For example: PayPal payments have reference and customer reference properties. In order to access these properties you have to cast the PaymentResponse to the PayPalPaymentResponse and access the Detail property.

Below is an example of accessing the iban of an ideal payment response.

```csharp
var idealPaymentResponse = paymentResponse as IdealPaymentResponse;
if (idealPaymentResponse != null)
{
    var iban = idealPaymentResponse.ConsumerAccount;
}
```

**Comment by tustc79** [comment]
evanderwaal@ntfu.nl

Op do 18 jun. 2020 om 17:27 schreef kryptonite <notifications@github.com>:

**Comment by tustc79** [comment]
Hi kryptonite,

That works perfect.
Bedankt!
