### ISSUE TITLE
Problem getting the orderResponse using the orderRequest

### ISSUE THREAD

**Issue by PauwelsPieter** [Viincenttt/MollieApi#187]
Hi,

I hope this is the correct way of asking this question...
In the "README" at number 9 about the Order API there is a chapter to create a new order. The first code block contains the following line at the end:
`OrderResponse result = await orderClient.CreateOrderAsync(orderRequest);`

But when I want to use this, I get the following error:
![image](https://user-images.githubusercontent.com/57799581/86848287-f7f31680-c0ad-11ea-9cb2-2ad40839acb8.png)

Thanks for checking this issue and thanks in advance for helping me out.
Feel free to ask any unclear points I haven't mentioned.

**Comment by Viincenttt** [comment]
Hi @PauwelsPieter ,

Can you show me which values you are sending to the Mollie API? One of the possible reasons you could be getting this error is because you are passing an invalid amount to the API. A common mistake is that "100,00" is passed instead of "100.00". If this is the issue, you can also use the `Amount(string currency, decimal amount)`, which should take care of this for you. 

For further help, please include the `OrderRequest` values you are sending. 

Kind regards,
Vincent

**Comment by PauwelsPieter** [comment]
> Hi @PauwelsPieter ,
> 
> Can you show me which values you are sending to the Mollie API? One of the possible reasons you could be getting this error is because you are passing an invalid amount to the API. A common mistake is that "100,00" is passed instead of "100.00". If this is the issue, you can also use the `Amount(string currency, decimal amount)` constructor, which should take care of this for you.
> 
> For further help, please include the `OrderRequest` values you are sending.
> 
> Kind regards,
> Vincent

First of all thanks alot for your response.
I tried used the `Amount(string currency, decimal amount)` constructor, but I still got a value missing or wrong somewhere I think, beceause I still get the same error. The values I am sending through are the following:


                   `List<OrderLineRequest> OrderLineList = new List<OrderLineRequest>();
                    foreach(product in cart){
                        OrderLineRequest Orderline = new OrderLineRequest();
                        Orderline.Name = "theProductName";
                        Orderline.Quantity = Amount;       (integer of the quantity)
                        Orderline.UnitPrice = new Amount(Currency.EUR, Convert.ToDecimal(ProductPrice));
                        Orderline.TotalAmount = new Amount(Currency.EUR, Convert.ToDecimal(Amount * ProductPrice));
                        Orderline.VatRate = "21.00";
                        Orderline.VatAmount = new Amount(Currency.EUR, Convert.ToDecimal((Amount * ProductPrice)*0.21));

                        OrderLineList.Add(Orderline);
                    }

                    IOrderClient orderClient = new OrderClient("myTestAPIKey");
                    OrderRequest orderRequest = new OrderRequest()
                    {
                        Amount = new Amount(Currency.EUR, Convert.ToDecimal(Total)),         (Total = double amount)
                        OrderNumber = OrderID.ToString(),             (OrderID = unique number I use in my database)
                        Lines = OrderLineList,
                        BillingAddress = new OrderAddressDetails()
                        {
                            GivenName = "Pieter",
                            FamilyName = "Pauwels",
                            Email = "myemail@gmail.com",
                            City = "myCity",
                            Country = "myCountry" (in ISO 3166-1 alpha-2 format),
                            PostalCode = "myPostalCode",
                            StreetAndNumber = "myStreet myHouseNumber"
                        },
                        RedirectUrl = "http://www.google.be",
                        Locale = Locale.en_US
                    };
                    OrderResponse orderResponse = await orderClient.CreateOrderAsync(orderRequest);`

**Comment by Viincenttt** [comment]
Hi @PauwelsPieter ,

I think the recommended approach is to add an extra order line that contains the shipping fee. One of the possible order line details type is `shipping_fee`. Take a look at this part of the Mollie documentation for more information:
https://docs.mollie.com/reference/v2/orders-api/create-order#order-line-details

Kind regards,
Vincent

**Comment by PauwelsPieter** [comment]
> Hi @PauwelsPieter ,
> 
> I think the recommended approach is to add an extra order line that contains the shipping fee. One of the possible order line details type is `shipping_fee`. Take a look at this part of the Mollie documentation for more information:
> https://docs.mollie.com/reference/v2/orders-api/create-order#order-line-details
> 
> Kind regards,
> Vincent

Thanks again for your repy, this is exacly what I needed! Thanks for your help!
