### ISSUE TITLE
Metadata should probably be an object, or a collection, not a string

### ISSUE THREAD

**Issue by abelbraaksma** [Viincenttt/MollieApi#19]
Metadata is a free-form JSON object in Mollie's api. In your mapping it is a string. Setting it to "just" a string will fail with a dynamic error. Setting it to a JSON string (with JSON.NET, NewtonSoft.Json etc) works though, and the result needs to be parsed back into a dynamic type.

For instance, something like the following works (for retrieving it):

```
result = mollieClient.GetPaymentAsync(paymentId).Result;
if (!String.IsNullOrEmpty(result.Metadata))
{
    // be careful, must be dynamic!
    dynamic metaData = Newtonsoft.Json. JsonConvert.DeserializeObject<dynamic>(result.Metadata);
    orderConfirmationEmail = metaData.emailTo;
}
```

The syntax, if you'd device the JSON by hand, for the above code fragment, could look like this:

```
var orderConfirmationMail = Request.Form["email"];
PaymentRequest paymentRequest = new PaymentRequest()
{
    Amount = 123.45M,
    Description = "my first pony",
    RedirectUrl = "http://xyz.com",
    Metadata = "{ \"emailTo\": \"" + orderConfirmationEmail + "\" }"  // ouch, ugly...
};
```

I'm not saying there's something seriously broken or so, but being able to send metadata with a request painlessly would certainly be beneficial. Perhaps you can turn the type into a collection? Or create a specific action, say `SetMetadataFromJson(string json)` and `SetMetadataFromCollection(ICollection data)`. Just some suggestions which I think would make using this library even easier ;).

Btw, let's not forget that I had little to no trouble using your library. After a few moments of "getting used to", I managed to use it effectively and easily. Thanks for your excellent work!

**Comment by Viincenttt** [comment]
Another solution could be to use the Newtonsoft.Json.Linq.JObject class. This will allow you to easily read/write any values of a json object. This will also allow you to easily serialize your own custom metadata class to the MetaData property. For example: 
Converting JObject to your own class:
``
MyCustomMetaDataClass metaData = JObject.Parse.ToObject<MyCustomMetaDataClass>();
``
Writing your own metadata class to a JObject:
``
JObject jsonObject = JObject.FromObject(metaData);
``

PS: Thank you for your feedback. If you have any more suggestions on how to make this library even better or have any suggestions on how to improve the documentation of the library I will be happy to add/change features or documentation. Also, feel free to make any changes yourself and create a pull request. 

Kind regards,
Vincent

**Comment by Viincenttt** [comment]
Version 1.4.4 has added support for the serialization and deserialization of custom metadata classes. You can now add metadata using the SetMetadata method on the PaymentRequest class and retrieve custom metadata classes using the GetMetadata method on the PaymentResponse class.
