### ISSUE TITLE
Could not create SSL/TLS secure channel

### ISSUE THREAD

**Issue by ggegos** [Viincenttt/MollieApi#190]
Hi, 

Thanks so much for this Libray.
The library was working fine, but suddenly I got the following exception:

System.Net.WebException: The request was aborted: Could not create SSL/TLS secure channel. bij System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult) bij System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar) --- Einde van intern uitzonderingsstackpad --- bij System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() bij System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) bij Mollie.Api.Client.BaseMollieClient.d__7`1.MoveNext() --- Einde van stacktracering vanaf vorige locatie waar uitzondering is opgetreden --- bij System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() bij System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) bij Mollie.Api.Client.BaseMollieClient.d__9`1.MoveNext() --- Einde van stacktracering vanaf vorige locatie waar uitzondering is opgetreden --- bij System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() bij System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) bij Mollie.Api.Client.PaymentClient.d__2.MoveNext() --- Einde van stacktracering vanaf vorige locatie waar uitzondering is opgetreden --- bij System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() bij System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) bij System.Runtime.CompilerServices.TaskAwaiter`1.GetResult() bij EscapeAll.Utilities.MollieLibrary.d__1.MoveNext() in C:\Users\sogeg\source\repos\EscapeAll\EscapeAll\Utilities\Mollie.cs:regel 98

I call the paymentClient.GetPaymentAsync(providersPaymentId)

Any ideas why this is happening?

Thanks
George!

**Comment by neilboyd** [comment]
I don't know if this is related because I don't know your environment, but we've been getting the same error. The word is that it might be a bug in the latest .Net version.
https://developercommunity.visualstudio.com/content/problem/1179481/unable-to-create-ssl.html
https://github.com/Azure/azure-powershell/issues/13117

**Comment by Viincenttt** [comment]
SSL/TLS errors are usually an issue with the environment on which the application is running. I'm not able to provide any support on this unfortunatly.
