### ISSUE TITLE
Mapping fee-regions

### ISSUE THREAD

**Issue by arnetm** [Viincenttt/MollieApi#193]
Can we make sure that this package is robust for future code changes? It could be that new 'fee-regions' pop up. 

https://github.com/Viincenttt/MollieApi/blob/6d6384317ff15e40afe78e02a23d323b37678308/Mollie.Api/Models/Payment/Response/Specific/CreditCardPaymentResponse.cs#L93

**Comment by Viincenttt** [comment]
Could you explain what is not robust about this code? In case a new fee-region pops up, it will deserialize just fine. You just won't have a constant string that represents that specific value. 

In the past, the CreditCardFeeRegion was an enum, which would cause the deserialization to fail whenever Mollie added a new value. Now that the values are constant strings, this should no longer be an issue.

**Comment by arnetm** [comment]
Because https://github.com/Viincenttt/MollieApi/issues/191, it is clear that adding an extra response-field to the Mollie API breaks the integration for multiple parties.

Is there a way to prevent this type or errors in the future?

**Comment by Viincenttt** [comment]
It is not clear to me what the problem is you are referring to. As far as I can see #191 was solved by updating to the latest version of the library. With this latest version, the library will no longer crash when Mollie adds new values, as the CreditCardFeeRegion has been converted from an enum to a list of constant strings.

**Comment by Viincenttt** [comment]
For more reference, take a look at this older GitHub issue. The commits I did to fix this issue are also included at the bottom:
https://github.com/Viincenttt/MollieApi/issues/113

**Comment by Viincenttt** [comment]
Issue has been resolved after e-mailing with arnetm
