### ISSUE TITLE
Error converting value

### ISSUE THREAD

**Issue by gijsstrik** [Viincenttt/MollieApi#194]
I get errors like:
Error converting value "intra-eu-corporate" to type 'System.Nullable`1[Mollie.Api.Models.Payment.Response.CreditCardFeeRegion]'. Path 'details.feeRegion', line 1, position 989.
Error converting value "domestic" to type 'System.Nullable`1[Mollie.Api.Models.Payment.Response.CreditCardFeeRegion]'. Path 'details.feeRegion', line 1, position 986.

When the webhook is called by mollie after a succesful payment (abbreviated):
                var PaymentReference = Request.Form["id"];

                // Create mollie client to get status of given payment
                var response = Task.Run(async () => await new PaymentClient(Properties.Settings.Default.mollie_api_key).GetPaymentAsync(PaymentReference)).GetAwaiter().GetResult();

Any changes I am not aware of?
Using version 2.0.7.1

**Comment by Viincenttt** [comment]
Hi @gijsstrik ,

This issue should be resolved if you update to version 2.1.0.0 or higher. Take a look at this issue for more information: https://github.com/Viincenttt/MollieApi/issues/191

Kind regards,
Vincent
