### ISSUE TITLE
Typo in app permission OnboardingRead (= "onboarding.write")

### ISSUE THREAD

**Issue by project01-wim** [Viincenttt/MollieApi#195]
Hi, ik vond een typo in volgende app permission. 

public const string OnboardingRead = "onboarding.write";

Ik had zelf de correctie wel willen doen, maar ik heb wat te weinig ervaring met git/github dus ik dacht het even op deze manier te laten weten ;). Knap werk deze wrapper trouwens!

**Comment by Viincenttt** [comment]
Fixed in PR #198 by yourself ;) I'll see when I can do a new release. Until then I'll keep this issue open so I won't forget about it.

**Comment by Viincenttt** [comment]
This issue is now fixed in version 2.1.0.2 of the library that I just released on NuGet.
