### ISSUE TITLE
Missing app permission: settlements.read

### ISSUE THREAD

**Issue by project01-wim** [Viincenttt/MollieApi#196]
Settlements API client is present, but permission is missing ("settlements.read").

**Comment by Viincenttt** [comment]
Fixed in PR #198 by yourself ;) I'll see when I can do a new release. Until then I'll keep this issue open so I won't forget about it.

**Comment by Viincenttt** [comment]
This issue is now fixed in version 2.1.0.2 of the library that I just released on NuGet.
