### ISSUE TITLE
MollieModels.Payment.PaymentStatus.Charged_Back removed?

### ISSUE THREAD

**Issue by c-lamont** [Viincenttt/MollieApi#200]
Just updated to 2.1 and I noticed that the `Charged_Back` status has been removed. 
Is it somewhere else, or is there another value I need to use that evaluates to the payment being charged back?

**Comment by Viincenttt** [comment]
Hi c-lamont,

Take a look at the Mollie API documentation. The status charged back does not exist:
https://docs.mollie.com/payments/status-changes

Kind regards,
Vincent
