### ISSUE TITLE
Unprocessable Entity - Non-existent query parameter "testmode" for this API call. Did you mean: "resource"?

### ISSUE THREAD

**Issue by tombeuckelaere** [Viincenttt/MollieApi#204]
When using the latest version of the libary, I'm getting an issue when fetching the payment methods for a test API key.

**Called method**

```
var useTestMode = true;
 paymentMethodClient.GetPaymentMethodListAsync("oneoff ","en_US", null, false, false, null, useTestMode,null);
```

**Thrown exception**

`One or more errors occurred. (Unprocessable Entity - Non-existent query parameter "testmode" for this API call. Did you mean: "resource"?)'`

**Comment by Viincenttt** [comment]
Hi @tombeuckelaere ,

I've taken a look at the Mollie API documentation. It would seem that the testmode parameter is only available if you are using  organization access tokens. This means that you also have to pass in the `profileId` parameter. Take a look at the following documentation for more information:
https://docs.mollie.com/reference/v2/methods-api/list-methods#access-token-parameters

Kind regards,
Vincent
