### ISSUE TITLE
Error converting value "domestic" to type System.Nullable

### ISSUE THREAD

**Issue by mycd1234** [Viincenttt/MollieApi#207]
Hi,

I'm using version 2.1.0.1 and today I got the following message : Error converting value "domestic" to type 'System.Nullable`1[Mollie.Api.Models.Payment.Response.CreditCardFeeRegion]'. Path 'details.feeRegion', line 1, position 946.
Requested value 'domestic' was not found.

This is happening with a customer who tries to pay with CC.

Issue [#191](https://github.com/Viincenttt/MollieApi/issues/191) says that it should be solved after version 2.1.0.0 but it seems not to be.

Could you please help on how to manage this ?

Thanks in advance

Cédric

**Comment by Viincenttt** [comment]
Hi @mycd1234 

Are you sure you are using the latest version? I have just checked the master branch and there is no longer a type called `Mollie.Api.Models.Payment.Response.CreditCardFeeRegion` inside of the code. This enum was removed back in march, in the following commit:
https://github.com/Viincenttt/MollieApi/commit/99444890939bdd5887133e3aacb4dd3732818fe1#diff-486eb8a916276f3f84743bcab4b7f133d0eae7c16b203ed9c1fce9d27a4d4946

**Comment by mycd1234** [comment]
> Hi @mycd1234
> 
> Are you sure you are using the latest version? I have just checked the master branch and there is no longer a type called `Mollie.Api.Models.Payment.Response.CreditCardFeeRegion` inside of the code. This enum was removed back in march, in the following commit:
> [9944489#diff-486eb8a916276f3f84743bcab4b7f133d0eae7c16b203ed9c1fce9d27a4d4946](https://github.com/Viincenttt/MollieApi/commit/99444890939bdd5887133e3aacb4dd3732818fe1#diff-486eb8a916276f3f84743bcab4b7f133d0eae7c16b203ed9c1fce9d27a4d4946)

Hi,

First thanks for your quick answer.
I checked again and it seems I forgot to copy the last dll from the staging environment to production.
So the problem occurred with version 2.0.5.0 while my staging uses 2.1.0.0.
I copied the 2.1.0.0 now so it should be OK.
I have to apologize for the time you spent due to my fault.
Thanks again.

**Comment by Viincenttt** [comment]
No problem!
