### ISSUE TITLE
Zipcode required

### ISSUE THREAD

**Issue by rjdegroot** [Viincenttt/MollieApi#209]
Hi,

When creating a new order and leave the zipcode blanc I get an error. Since you not always have a zipcode (not all countries use this) it should be optional I think? 

Can this be changes or is Mollie  responsible for this?

Regards,
Ronald

**Comment by Viincenttt** [comment]
Hi @rjdegroot ,

Your best bet is to contact Mollie support and ask them this question. This library doesn't do any content validation. All validations are done by Mollie on the server side. 

Kind regards,
Vincent
