### ISSUE TITLE
Duedate with iDeal payment

### ISSUE THREAD

**Issue by paulwitmond** [Viincenttt/MollieApi#210]
Hi,

How can we set the DueDate when we create an iDeal payment ?

Currently all our payment request expire in 15 minutes and that's way too short

This is the current code:

 PaymentRequest paymentRequest = new PaymentRequest()
                    {
                        Amount = new Amount(Currency.EUR, DocTotal),
                        Description = "Badé faktuur " + DocNum,
                        RedirectUrl = "https://bade.biz",
                       Method = PaymentMethod.Ideal
                    };
                    PaymentResponse result = await paymentClient.CreatePaymentAsync(paymentRequest, includeQrCode: true);
                    IdealPaymentResponse idealPaymentResult = result as IdealPaymentResponse;
                    IdealPaymentResponseDetails idealPaymentDetails = idealPaymentResult.Details;

**Comment by Viincenttt** [comment]
Hi @paulwitmond 

I've taken a look at the Mollie API documentation and I don't see any way to set a due date on a iDeal payment. So I'm afraid theres nothing I can do from my side. Perhaps you could contact Mollie and ask them this question. 

Kind regards,
Vincent
