### ISSUE TITLE
Getting test payment methods gives error.

### ISSUE THREAD

**Issue by cmolendijk** [Viincenttt/MollieApi#211]
When using the PaymentMethodClient with the GetPaymentMethodListAsync you cannot set the parameter TestMode to true. You will get the error:

`Unprocessable Entity - Non-existent query parameter "testmode" for this API call. Did you mean: "resource"?`

Resulting that you cannot get the test environment payment methods.

**Comment by Viincenttt** [comment]
The testmode is used by using a test API key. You don't have to set the testmode parameter. The testmode parameter is only used when you are using oauth authentication to connect with the API.
