### ISSUE TITLE
Missing MandateId on GetSubscriptionAsync

### ISSUE THREAD

**Issue by foppenm** [Viincenttt/MollieApi#212]
Hi,

Thank you for all your work into this project! I noticed that on the Subscription API there is a SubscriptionResponse, used for GetSubscriptionAsync(), which currently does not have a property MandateId. The mollie api docs indicate there is one. See: https://docs.mollie.com/reference/v2/subscriptions-api/get-subscription
I'm using version 2.1.0.3

If you agree I can put in the work to implement it myself. 

Let me know :)

**Comment by Viincenttt** [comment]
Hi @foppenm ,

Thanks for reporting this. I have added the `MandateId` property to the `SubscriptionReponse`. If you update the package to version 2.1.0.4, you'll be able to use this property.

Kind regards,
Vincent

**Comment by foppenm** [comment]
Thank you for the quick response and fix, really appreciated! 👍🏻
