### ISSUE TITLE
How to initiate a Giropay or Bancontact payment request?

### ISSUE THREAD

**Issue by flo-rider** [Viincenttt/MollieApi#216]
I downloaded and built the latest version today. I can create new creditcard payment requests like so:

    Mollie.Api.Models.Payment.Request.CreditCardPaymentRequest paymentRequest = new Mollie.Api.Models.Payment.Request.CreditCardPaymentRequest();

I can do the same for PayPal, iDeal, Przelewy24.

However, I can't seem to do the same for Giropay or Bancontact, e.g. `Mollie.Api.Models.Payment.Request.GiropayPaymentRequest paymentRequest = new Mollie.Api.Models.Payment.Request.GiropayPaymentRequest();`

How do I initiate a Giropay or Bancontact payment request?

**Comment by Viincenttt** [comment]
Hi @flo-rider ,

Giropayments and Bancontact payment do not have any payment specific properties and therefor do not have their own separate class. You can create a Giropayment/Bancontact payment, using the `PaymentRequest` class and by setting the `Method` to `PaymentMethod.Bancontact` or `PaymentMethod.Giro`. 

Take a look at the readme.md or the example project for concrete examples on how to do this.

Kind regards,
Vincent

**Comment by flo-rider** [comment]
Thank you Vincent! I tried your suggestion:

	
    Mollie.Api.Models.Payment.Request.PaymentRequest paymentRequest = new Mollie.Api.Models.Payment.Request.PaymentRequest();
    paymentRequest.Method = PaymentMethod.Bancontact;
    paymentRequest.Amount = new Amount(mollieCurrency, priceInclTaxAndTransactionCostsDotDecimal);
    paymentRequest.Description = paymentDescription;
    paymentRequest.RedirectUrl = paymentRedirectUrl;
    var paymentResponse = await paymentClient.CreatePaymentAsync(paymentRequest);


However, I then get the error:

> Unprocessable Entity - The payment method is invalid

On line `var paymentResponse = await paymentClient.CreatePaymentAsync(paymentRequest);`	

Can you help?
