### ISSUE TITLE
Invalid oauth token when in testing mode

### ISSUE THREAD

**Issue by CornelisS** [Viincenttt/MollieApi#217]
I am trying to create a payment using your package and setting TestMode on true and setting the ProfileId gives me an exception with the message: "The provided token isn't an oauth token"

I checked your code and it seems the following fragment of code might be the root of the cause of the exception. 

```
 if (!string.IsNullOrWhiteSpace(paymentRequest.ProfileId) || paymentRequest.Testmode.HasValue || paymentRequest.ApplicationFee != null) {
        this.ValidateApiKeyIsOauthAccesstoken();
    }  
```
This is in PaymentClient.cs line 18.

The method ValidateApiKeyIsOauthAccesstoken() checks if my ApiKey starts with access_ but in my case I have a test ApiKey which starts with test_ and that triggers the throw exception in that method. 

I think either the if-statement should change or the ValidateApiKeyIsOauthAccesstoken should accept ApiKeys starting with test_ 

And looking at the if-statement I think it is a bit odd that there is only a check on Testmode having a value but not checking the actual value. Why is that?

**Comment by Viincenttt** [comment]
Hi @CornelisS ,

The testmode parameter should only be set if you are using an oauth token. If you are using a regular test api key, all payments are automatically created as test payments. 

Take a look at the Mollie documentation:
https://docs.mollie.com/reference/v2/payments-api/create-payment

The `testmode` parameter is listed under "Access token parameters", meaning you should not use it at all, unless you are using a oauth token. 

Kind regards,
Vincent
