### ISSUE TITLE
A strongly-named assembly is required

### ISSUE THREAD

**Issue by abereznyi** [Viincenttt/MollieApi#22]
For using Mollie.Api in in a signed .NET assembly, Mollie.Api has to be signed too.
Also RestSharp used by Mollie.Api will need need be signed as well.

NuGet package Brutal.Dev.StrongNameSigner.2.1.0 can be used to add signatures  in .csproj, like:

....
  <Target Name="BeforeBuild">
    <Exec ContinueOnError="false" Command="$(SolutionDir)\packages\Brutal.Dev.StrongNameSigner.2.1.0\build\StrongNameSigner.Console.exe -in $(SolutionDir)\packages\Mollie*\lib\net45*" />
    <Exec ContinueOnError="false" Command="$(SolutionDir)\packages\Brutal.Dev.StrongNameSigner.2.1.0\build\StrongNameSigner.Console.exe -in $(SolutionDir)\packages\RestSharp*\lib\net4*" />
  </Target>
  <Target Name="AfterBuild">
  </Target>
</Project>

Could you add signatures? 

Thanks a lot for adding KBC pay type support today so fast :)

**Comment by Viincenttt** [comment]
Hi Aberznyi,

If you require a strongly signed assembly, please download the source and sign it yourself. 

Kind regards,
Vincent
