### ISSUE TITLE
Registratie probleem

### ISSUE THREAD

**Issue by Daan1606** [Viincenttt/MollieApi#222]
Ha Vincent,

Dank voor de content die je op Github deelt, heeft me al enorm geholpen.
Echter loop ik vast na een IDEAL registratie i.c.m. het wegschrijven van de aangemaakte gebruiker gegevens naar Azure SQL Database. Hierdoor wordt de aangemaakte gebruiker niet aangemaakt in de database, ondanks dat de registratie wel is geslaagd. Heb jij een idee?

Thanks alvast.

**Comment by Viincenttt** [comment]
Hi @Daan1606 ,

I'm glad that the documentation has been helpful. If you have any ideas to improve them further, please let me know. 

Regarding your issue with Azure SQL database: Unfortunately, I cannot help you with issues that are not related to the Mollie client library. If you have any issues with the Mollie library, feel free to reply to this issue or create a new issue. 

Kind regards,
Vincent
