### ISSUE TITLE
Please add changePaymentState href to Models for better testing recurring payments.

### ISSUE THREAD

**Issue by zedL** [Viincenttt/MollieApi#228]
![image](https://user-images.githubusercontent.com/12039628/112717647-6141e080-8eee-11eb-9966-d025add84329.png)

=> https://docs.mollie.com/payments/recurring

**Comment by Viincenttt** [comment]
Hi @zedL , 

This feature has been added and is now available in version 2.1.0.6 of the Mollie library.

Kind regards,
Vincent
