### ISSUE TITLE
Please add AmountChargedBack to PaymentResponseModel like you did for AmountRemaining, AmountCaptured...

### ISSUE THREAD

**Issue by zedL** [Viincenttt/MollieApi#229]
![image](https://user-images.githubusercontent.com/12039628/114075161-839c0c80-98a5-11eb-9637-a5e576e5e0c6.png)

**Comment by Viincenttt** [comment]
Hi @zedL , 

This feature has been added and is now available in version 2.1.0.6 of the Mollie library.

Kind regards,
Vincent
