### ISSUE TITLE
NuGet not compatible with .Net Core 1.x

### ISSUE THREAD

**Issue by jphellemons** [Viincenttt/MollieApi#23]
Please recompile or .net Standard https://blogs.msdn.microsoft.com/dotnet/2016/09/26/introducing-net-standard/

````
Installing RestSharp 105.2.3.
Installing Mollie.Api 1.3.7.
Package Mollie.Api 1.3.7 is not compatible with netcoreapp1.0 (.NETCoreApp,Version=v1.0). Package Mollie.Api 1.3.7 supports: net45 (.NETFramework,Version=v4.5)
Package RestSharp 105.2.3 is not compatible with netcoreapp1.0 (.NETCoreApp,Version=v1.0). Package RestSharp 105.2.3 supports:
  - monoandroid10 (MonoAndroid,Version=v1.0)
  - monotouch10 (MonoTouch,Version=v1.0)
  - net35 (.NETFramework,Version=v3.5)
  - net40 (.NETFramework,Version=v4.0)
  - net40-client (.NETFramework,Version=v4.0,Profile=Client)
  - net45 (.NETFramework,Version=v4.5)
  - net451 (.NETFramework,Version=v4.5.1)
  - net452 (.NETFramework,Version=v4.5.2)
  - net46 (.NETFramework,Version=v4.6)
  - sl5 (Silverlight,Version=v5.0)
  - wp8 (WindowsPhone,Version=v8.0)
  - wp81 (WindowsPhone,Version=v8.1)
  - xamarinios10 (Xamarin.iOS,Version=v1.0)
One or more packages are incompatible with .NETCoreApp,Version=v1.0.
````

**Comment by Viincenttt** [comment]
Hi jphellemons,

I am sorry for my late response. MollieAPI uses the RestSharp library to make API calls. Unfortunatly, RestSharp currently doesn't support .NET core. Please see this issue: https://github.com/restsharp/RestSharp/issues/664

I will continue to monitor the situation. If RestSharp doesn't update their library soon, I will have to change to a different library.

**Comment by Viincenttt** [comment]
Hi jphellemons,

Today I have removed RestSharp from the project and have replaced it with the standard HttpClient. I have also converted the Mollie.Api project to a .NET standard project. This should allow you to reference the library in .NET core projects from now on.

Kind regards,
Vincent

**Comment by Mahesh1234ctr1** [comment]
Hi,
I am facing this issues ->
Package RestSharp 104.0.0 is not compatible with netcoreapp1.0 (.NETCoreApp,Version=v1.0). Package RestSharp 104.0.0 supports: ????

**Comment by Mahesh1234ctr1** [comment]
Hi,
I am facing this issues -> while install rest sharp 
Package RestSharp 104.0.0 is not compatible with netcoreapp1.0 (.NETCoreApp,Version=v1.0). Package RestSharp 104.0.0 supports: May i know pls what is solution for this ????

**Comment by Mahesh1234ctr1** [comment]
Hi,
i am using "HttpClient" post the data my endpoint is expecting XML data as param but i am facing below issue
CallEndPint(string requestXmlForSale){
var response = await client.PostAsync(requestXmlForSale);
}
error-> cannot convert 'string' to system.net.httpcontent --> how to solve this issue???

**Comment by Viincenttt** [comment]
Hi Mahesh1234ctr1,

Is this related to my library? Which library method are you using? 

Kind regards,
Vincent
