### ISSUE TITLE
Missing configure.await in BaseMollieClient

### ISSUE THREAD

**Issue by Bodewes** [Viincenttt/MollieApi#231]
In the BaseMollieClient one async call of the `SendHttpRequest` is missing a `configureAwait(false)`. 
 
Location: https://github.com/Viincenttt/MollieApi/blob/e87b6323a3bd0cf4cbe800997bdf5bc352d22255/Mollie.Api/Client/BaseMollieClient.cs#L51

The other calls were fixed with the resolution of #163. This calls seems to have been missed. 

I ran into a deadlock using a call that lists all mandates. (I know, I should use Async all the way, but that is just simply not possible in our huge code base at the moment).

**Comment by Viincenttt** [comment]
Hi @Bodewes , 

This bug has now been fixed. If you update to version 2.1.0.6 of the Mollie library, you should no longer encounter any issues :)

Kind regards,
Vincent
