### ISSUE TITLE
 Update Json parsing to ignore datetime in string

### ISSUE THREAD

**Issue by Bodewes** [Viincenttt/MollieApi#232]
There is a (strange?) default setting in Newtonsoft.Json that allows the parser to inspect strings and try to parse them as a DateTime. Even if the target type is a `string`. See https://github.com/JamesNK/Newtonsoft.Json/issues/862 for more details. It even seems to parse a string as datetime and then uses the toString()-method to write a string again on deserializing.

On the image below, on the right is the raw-output from the api, on the left is the value of the MandateResponse.SignatureDate-field of the response model class. Notice that the string value has been mangled into a en-us DateTime represention with a time-part.
![image](https://user-images.githubusercontent.com/7304010/114925162-0df8e900-9e2f-11eb-98af-196a2f275a6b.png)

There is a setting to stop the automagic-parsing of dates in string: 
https://www.newtonsoft.com/json/help/html/T_Newtonsoft_Json_DateParseHandling.htm

**Comment by Viincenttt** [comment]
Could you perhaps give me some sample code I could use to reproduce this issue?
