### ISSUE TITLE
InvoiceID in Settlement Response

### ISSUE THREAD

**Issue by calves07** [Viincenttt/MollieApi#234]
Hey,

According to the [official documentation](https://docs.mollie.com/reference/v2/settlements-api/get-settlement), settlement responses contain information about the invoice ID which before came in the settlement object itself but now is inside each monthly period but looks like this project does not support that yet or am I wrong?

Regards.

**Comment by Viincenttt** [comment]
Hi @calves07  ,

This feature has been added and is now available in version 2.1.0.7 of the Mollie library.

Kind regards,
Vincent
