### ISSUE TITLE
RefundResponse.SettlementId missing

### ISSUE THREAD

**Issue by G-Mueller** [Viincenttt/MollieApi#235]
Mollie's API documentation mentions a "settlementId" in refund objects:
https://docs.mollie.com/reference/v2/refunds-api/get-refund

This field is missing in class Mollie.Api.Models.Refund.RefundResponse.

**Comment by calves07** [comment]
It's possible there isn't a settlement for that refund yet so that field may be null.

**Comment by G-Mueller** [comment]
That's true, but class Mollie.Api.Models.Refund.RefundResponse does not have any property to hold the SettlementId.
Or did I miss something?

**Comment by Viincenttt** [comment]
Hi @G-Mueller ,

This feature has been added and is now available in version 2.1.0.7 of the Mollie library.

Kind regards,
Vincent
