### ISSUE TITLE
Configure MollieAPI to use TLS1.2

### ISSUE THREAD

**Issue by flo-rider** [Viincenttt/MollieApi#236]
I received an email today from Mollie (translated):
"We will be disabling TLS 1.0 and 1.1 soon. You are receiving this email because you have connected to our servers via the TLS 1.0 or 1.1 protocol in the last 30 days."

I use 2 versions of Mollie API on 2 different websites:
v2.0.6.0 and v2.1.0.5

I was checking the release notes from v2.0.6.0 up to the latest and nowhere did I see that TLS1.2 was added to the code. So I'm presuming it's not an upgrade I need to do, but rather configure my `PaymentClient` object to use TLS1.2. 

So how can I configure MollieAPI to use TLS1.2?

**Comment by Viincenttt** [comment]
Hi @flo-rider ,

Take a look at this Stackoverflow post: https://stackoverflow.com/a/22251844

The TLS version is negotiated by the server and the client. This library uses the HttpClient class to make requests to the Mollie API. Depending on your OS and .NET version, there are various steps you need to take to enable TLS 1.2 support. However, there is nothing I can configure from the library side. 

> Answer2: If the server you are connecting to has disabled SSL, TLS 1.0, and 1.1 and you are still running .NET framework 4.5(or below) you need to make a choice
> 
> Upgrade to .Net 4.6+ (Supports TLS 1.2 by default)
> Add registry changes to instruct 4.5 to connect over TLS1.2 ( See: salesforce writeup for compat and keys to change OR checkout IISCrypto see Ronald Ramos answer comments)
> Add application code to manually configure .NET to connect over TLS1.2 (see Ronald Ramos answer)

Kind regards,
Vincent

**Comment by kloarubeek** [comment]
@flo-rider I got the same email. I have a website running with .Net Framework 4.8. You can inject [a proper `HttpClient`](https://stackoverflow.com/a/57002553/2276157) into the Mollie `PaymentClient`:

```c#
var client = new PaymentClient("MollieApiKey", new HttpClient(new HttpClientHandler() { SslProtocols = SslProtocols.Tls12 }));
```

@Viincenttt is it an idea to adjust the [BaseMollieClient](https://github.com/Viincenttt/MollieApi/blob/83d35617604743e565067b43031b969bd6c89504/Mollie.Api/Client/BaseMollieClient.cs#L27) and create a Tls12 based HttpClient if it's not provided? (same for line 34)

**Comment by Viincenttt** [comment]
Thank you for the suggestion, I will do some more research on this :) I'll look into it in the weekend.

**Comment by flo-rider** [comment]
> @flo-rider I got the same email. I have a website running with .Net Framework 4.8. You can inject [a proper `HttpClient`](https://stackoverflow.com/a/57002553/2276157) into the Mollie `PaymentClient`:
> 
> ```cs
> var client = new PaymentClient("MollieApiKey", new HttpClient(new HttpClientHandler() { SslProtocols = SslProtocols.Tls12 }));
> ```
> 
> @Viincenttt is it an idea to adjust the [BaseMollieClient](https://github.com/Viincenttt/MollieApi/blob/83d35617604743e565067b43031b969bd6c89504/Mollie.Api/Client/BaseMollieClient.cs#L27) and create a Tls12 based HttpClient if it's not provided? (same for line 34)

I'm running 4.8 too and your solution seems to work...thanks! Hopefully I won't be shut down in 30 days ;-P

**Comment by kloarubeek** [comment]
Cool! I already asked Mollie if they can verify if this solution uses TLS12. I'll let you guys kow!

**Comment by Viincenttt** [comment]
Thank you for the suggestion.

I have found the following article from Microsoft, which recommends that you should not set the TLS version in your code. If you are using .NET framework 4.7 or higher, .NET will use the default OS TLS version. Also, if you are using Windows Server 2008 or lower, you need to install and enable TLS 1.2 support manually. Source: https://docs.microsoft.com/en-us/dotnet/framework/network-programming/tls

Therefore, I am hesitant to change any code in the library.

**Comment by kloarubeek** [comment]
Hmm, makes sense. Then I would keep it for now, you can easily change it yourself.

I also got an answer from Mollie: an automated process verifies if you use the correct TLS version. So if you don't receive an email about this in June, then you fixed it 😄.

**Comment by sandlands** [comment]
I have just (June 23 11:07) received a second warning e-mail from Mollie (after not taking any action until now). @kloarubeek Can you verify you didn't receive the second e-mail from Mollie, so we know this solution works?

**Comment by kloarubeek** [comment]
@sandlands I didn't get any message, so my fix works 🎉
