### ISSUE TITLE
BIC for bancontact payments

### ISSUE THREAD

**Issue by MichielCornilleESC** [Viincenttt/MollieApi#237]
I noticed [this commit](https://github.com/Viincenttt/MollieApi/commit/51c1e46210befb5ed963d53b75e63107ddf6b710)

Which added the IBAN for Bancontact payments.

The Mollie API seems to support BIC as well:

![image](https://user-images.githubusercontent.com/46707408/120328651-51c68580-c2eb-11eb-8d91-c4a813fee6c2.png)

Would it be possible to update the DTOs to the latest API version?
If you want I can create a PR just to add the consumerBIC property to the BankContactPaymentResponse DTO.

Thank sin advance

**Comment by Viincenttt** [comment]
Hi @MichielCornilleESC ,

If you can create a PR, I'll merge it and release a new version as soon as possible. I noticed we are also missing the `FailureReason` property. Could you add that as well?

Kind regards,
Vincent

**Comment by Viincenttt** [comment]
This is now live in version 2.1.0.8 of the library
