### ISSUE TITLE
Apple Pay is unavailable

### ISSUE THREAD

**Issue by flo-rider** [Viincenttt/MollieApi#241]
I'm unable to start a payment using Apple Pay. Even though Apple Pay is enabled in Mollie dashboard, when trying to start the payment I get a screen telling me "Apple Pay is unavailable"

My code to start this payment (which works with PayPal and other payment methods):

		Dim paymentRequest As New Mollie.Api.Models.Payment.Request.ApplePayPaymentRequest
		paymentRequest.Amount = New Amount(mollieCurrency, priceInclTaxAndTransactionCostsDotDecimal) ' "100.00"
		paymentRequest.Description = paymentDescription
		paymentRequest.RedirectUrl = paymentRedirectUrl
		Dim paymentResponse As PaymentResponse = Await paymentClient.CreatePaymentAsync(paymentRequest)
		Response.Redirect(paymentResponse.Links.Checkout.Href)

The screenshots:

![image](https://user-images.githubusercontent.com/7127039/121965317-21f89280-cd6d-11eb-9ea2-821f54e29c80.png)
![image](https://user-images.githubusercontent.com/7127039/121965330-2755dd00-cd6d-11eb-83dc-2a24d0ccd31e.png)

After the 2nd screen a redirect takes place and the transaction get status `canceled`

What's happening here?

**Comment by Viincenttt** [comment]
Hi @flo-rider ,

Your code seems fine to me. If a payment method is unavailable, please try contacting Mollie to ask them for help. I cannot help you on this issue, as I don't think this is an issue that is related to the library. 

Kind regards,
Vincent
