### ISSUE TITLE
invoiceId is missing on SettlementResponse

### ISSUE THREAD

**Issue by Marcel-van-Beuzekom** [Viincenttt/MollieApi#242]
GetSettlementsListAsync and GetSettlementAsync are resulting in a (list of) SettlementResponse. The JSON response contains an invoiceId but there is no invoiceId property on the response class.

https://docs.mollie.com/reference/v2/settlements-api/get-settlement

**Comment by Viincenttt** [comment]
Hi @Marcel-van-Beuzekom ,

The invoidId property has been deprecated. It can be found in the `Periods` property instead. 

Kind regards,
Vincent
