### ISSUE TITLE
PaymentLink Api Models not found in Nuget

### ISSUE THREAD

**Issue by drlee91** [Viincenttt/MollieApi#245]
![grafik](https://user-images.githubusercontent.com/73903360/123060328-ea43b780-d40a-11eb-9069-950ef026449e.png)

Hey there,

I'm trying to implement the  Payment Link Request, but cant find a reference.
` PaymentLinkRequest paymentLinkRequest = new PaymentLinkRequest();`

In the git-repository i can find the models:
```
@using Mollie.Api.Models.PaymentLink.Request
@using Mollie.Api.Models.PaymentLink.Response
```

But in my live-project with the nuget it cant find this models.
I updated the NuGet to the last version (2.1.0.7), is it integrated yet?

Thanks for help!

**Comment by joost-leisink** [comment]
This feature has been added to the development branch.
It's not yet merged with the master, so not released yet.

Is there an eta on when this will be released?

**Comment by drlee91** [comment]
the release would be really great, i really need this feature soon

**Comment by joost-leisink** [comment]
@Viincenttt  Is it possible to give an estimate on when this feature will be merged and released?

**Comment by Viincenttt** [comment]
The PaymentLink API only exists on the develop branch. It has not been released yet. I will try to release it soon, hopefully next weekend.

**Comment by Viincenttt** [comment]
This feature is now live in version 2.1.0.8 of the package. Sorry for taking a little bit longer then usual! :)

**Comment by drlee91** [comment]
thanks for the release, good work!
