### ISSUE TITLE
TLS 1.2 issue

### ISSUE THREAD

**Issue by SCCube** [Viincenttt/MollieApi#246]
Hey, 

Mollie sent us an email saying they will disable TLS 1.0 and TLS 1.1. We need to use TLS 1.2 instead. 

We are trying this locally on my pc, on which we disabled TLS 1.0 and TLS 1.1 in the registry (Protocols/TLS1.0/Client). 
When running this code in our project:
`payment = new MolliePaymentController().Create(price, paymentDescription, redirectUrl, webhookUrl);
`
We receive 3 errors: 
- HttpRequestException: An error occurred while sending the request.
- WebException: The underlying connection was closed: An unexpected error occurred on a receive.
- Win32Exception: The client and server cannot communicate, because they do not possess a common algorithm

How can we fix this issue? Or are we going about this the wrong way?

We are working with .NET Framework 4.7.2

Thanks!

**Comment by Viincenttt** [comment]
Hi @SCCube 

This issue has come up before here: https://github.com/Viincenttt/MollieApi/issues/236

I'm not sure how to reproduce it locally, but the TLS version that is used is dependant on the OS and .NET version you are using. Depending on these factors, various fixes are available. Take a look at the following link from Microsoft if you want to take see which solution is best for your OS and .NET version: https://docs.microsoft.com/en-us/dotnet/framework/network-programming/tls

Kind regards,
Vincent
