### ISSUE TITLE
Unable to build project rzc discover exited with code -2147450730

### ISSUE THREAD

**Issue by DuraScrin** [Viincenttt/MollieApi#247]
I was unable to build this project with VS 2019 ver 16.10.0

Error: rzc discover exited with code -2147450730

dotnet build command output:
 Determining projects to restore...
C:\Program Files\dotnet\sdk\5.0.300\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.EolTargetFrameworks.targets(28,5): warning NETSDK1138: The target framework 'netcoreapp2.2' is out of support and will not receive security updates in the future. Please refer to https://aka.ms/dotnet-core-support for more information about the support policy. [C:\Users\Me\Downloads\MollieApi-development\Mollie.WebApplicationCoreExample\Mollie.WebApplicationCoreExample.csproj]
  All projects are up-to-date for restore.
C:\Program Files\dotnet\sdk\5.0.300\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.EolTargetFrameworks.targets(28,5): warning NETSDK1138: The target framework 'netcoreapp2.2' is out of support and will not receive security updates in the future. Please refer to https://aka.ms/dotnet-core-support for more information about the support policy. [C:\Users\Me\Downloads\MollieApi-development\Mollie.WebApplicationCoreExample\Mollie.WebApplicationCoreExample.csproj]
  Mollie.Api -> C:\Users\Me\Downloads\MollieApi-development\Mollie.Api\bin\Debug\netstandard1.2\Mollie.Api.dll
  Mollie.Api -> C:\Users\Me\Downloads\MollieApi-development\Mollie.Api\bin\Debug\net45\Mollie.Api.dll
  Mollie.Tests.Unit -> C:\Users\Me\Downloads\MollieApi-development\Mollie.Tests.Unit\bin\Debug\netcoreapp3.1\Mollie.Tests.Unit.dll
  Mollie.Tests.Integration -> C:\Users\Me\Downloads\MollieApi-development\Mollie.Tests.Integration\bin\Debug\netcoreapp3.1\Mollie.Tests.Integration.dll

  Bundler: Begin processing bundleconfig.json
  Bundler: Done processing bundleconfig.json
  It was not possible to find any compatible framework version
  The framework 'Microsoft.NETCore.App', version '2.0.9' was not found.
    - The following frameworks were found:
        3.1.15 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
        5.0.6 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

  You can resolve the problem by installing the specified framework and/or SDK.

  The specified framework can be found at:
    - https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=2.0.9&arch=x64&rid=win10-x64
C:\Users\Me\.nuget\packages\microsoft.aspnetcore.razor.design\2.2.0\build\netstandard2.0\Microsoft.AspNetCore.Razor.Design.CodeGeneration.targets(131,5): error : rzc generate exited with code -2147450730. [C:\Users\Me\Downloads\MollieApi-development\Mollie.WebApplicationCoreExample\Mollie.WebApplicationCoreExample.csproj]

Build FAILED.

C:\Program Files\dotnet\sdk\5.0.300\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.EolTargetFrameworks.targets(28,5): warning NETSDK1138: The target framework 'netcoreapp2.2' is out of support and will not receive security updates in the future. Please refer to https://aka.ms/dotnet-core-support for more information about the support policy. [C:\Users\Me\Downloads\MollieApi-development\Mollie.WebApplicationCoreExample\Mollie.WebApplicationCoreExample.csproj]
C:\Program Files\dotnet\sdk\5.0.300\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.EolTargetFrameworks.targets(28,5): warning NETSDK1138: The target framework 'netcoreapp2.2' is out of support and will not receive security updates in the future. Please refer to https://aka.ms/dotnet-core-support for more information about the support policy. [C:\Users\Me\Downloads\MollieApi-development\Mollie.WebApplicationCoreExample\Mollie.WebApplicationCoreExample.csproj]
C:\Users\Me\.nuget\packages\microsoft.aspnetcore.razor.design\2.2.0\build\netstandard2.0\Microsoft.AspNetCore.Razor.Design.CodeGeneration.targets(131,5): error : rzc generate exited with code -2147450730. [C:\Users\Me\Downloads\MollieApi-development\Mollie.WebApplicationCoreExample\Mollie.WebApplicationCoreExample.csproj]
    2 Warning(s)
    1 Error(s)

Time Elapsed 00:00:23.37
![MollieApi - Microsoft Visual Studio](https://user-images.githubusercontent.com/24371504/126865797-1760f32d-3c73-473a-9854-7d2c8d288214.png)

**Comment by Viincenttt** [comment]
Thanks for the notice. I'll try to update the example project to a newer version soon. In the mean time, you can exclude the example project. The Mollie.Api project is the one you'll need :)

**Comment by DuraScrin** [comment]
Thx. 
For now this project runs if you switch target framework to .NET Core 2.1 & run it in IIS. Not all components will works as expected but the project will compile.

**Comment by Viincenttt** [comment]
Hi @DuraScrin 

I have upgraded the example project to a .NET5 project, so it's completely up-to-date again. If you pull the latest version from the development or master branch, you should no longer receive any warnings/errors from visual studio.

Kind regards,
Vincent
