### ISSUE TITLE
Send paymentmethod issuer with create payment?

### ISSUE THREAD

**Issue by ab-Colin** [Viincenttt/MollieApi#248]
The Mollie API documentation states that you can send an issuer along with the (payment)method. In my case I would to send the iDeal issuer, Rabobank for example, with the create payment call. I would like to do this so that the checkout link redirects me directly to the specific issuer (bank) environment. Is this functionality missing from the current version of this MollieApi project or am I missing something?

**Comment by Viincenttt** [comment]
Hi @ab-Colin ,

Some payment methods, such as iDeal, have their own PaymentRequest class that you can use, which has additional/custom properties that are specific for the payment method. To set the issuer for a iDeal payment, you can use the following code:

```
var paymentRequest = new  IdealPaymentRequest() { Issuer = "ideal_INGBNL2A" }
await paymentClient.CreatePaymentAsync(paymentRequest);
```

Kind regards,
Vincent

**Comment by ab-Colin** [comment]
Thanks @Viincenttt :)

Nice work on this project!
