### ISSUE TITLE
Could not load file or assembly 'RestSharp'

### ISSUE THREAD

**Issue by okankocyigit** [Viincenttt/MollieApi#25]
I've installed nuget package of MollieApi, it has installed successfully with Restsharp 105.2.3.0.

I have simply add this code,

```
PaymentClient paymentClient = new PaymentClient("myapikey");
PaymentRequest paymentRequest = new PaymentRequest() {
    Amount = 100,
    Description = "Test payment of the example project",
    RedirectUrl = "http://google.com"
};

PaymentResponse paymentResponse = paymentClient.CreatePaymentAsync(paymentRequest).Result;
```
it has build and run, but on runtime I alwasy get this error,

```
Exception information: 
    Exception type: FileNotFoundException 
    Exception message: Could not load file or assembly 'RestSharp, Version=105.2.3.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
```

**Comment by okankocyigit** [comment]
![project](https://cloud.githubusercontent.com/assets/16730661/21961829/877c0f90-db25-11e6-8e30-e2a4bf199467.png)

**Comment by Viincenttt** [comment]
Hi Okan,

That's strange, what kind of project are you running? The only thing I can think of is that you might be running a .NET core project, which is currently not supported since RESTSharp doesn't support .NET core yet.

Kind regards,
Vincent

**Comment by okankocyigit** [comment]
It's a Web Api Project.

It's interesting that I have also [Plivo](https://github.com/plivo/plivo-dotnet) (installed via Nuget) which require RestSharp but Plivo has installed  RestSharpSigned.

So my project has Restsharp and RestsharpSigned.

If I remove RestSharpSigned and Plivo, Mollie Api is working.

I've also issued this problem on Plivo, will inform you.

Thanks.

**Comment by okankocyigit** [comment]
Ok, the problem is about Plivo they should check it.

I'm closing this issue, anybody who has this problem can look [here](https://github.com/plivo/plivo-dotnet/issues/33).
