### ISSUE TITLE
How can I pass credit card informations or other bancontact informations of customer

### ISSUE THREAD

**Issue by ByErdem** [Viincenttt/MollieApi#250]
Hello, 
I examined the examples here. Everything looks good at the begining. I entering the test api key to create payment request. But I noticed that, how the customer will enter the payment informations. I didn't see any example code related with this. Can you show me a solution for this?

**Comment by Viincenttt** [comment]
I'm not sure I understand. The customer enters the payment information after your website redirects him to the payment link that you get back from the Mollie API. If you want to limit the customer to specific payment methods, that is also possible. Take a look at the following example code: https://github.com/Viincenttt/MollieApi/issues/248

**Comment by Viincenttt** [comment]
Closing this one. Feel free to open a new issue if you are still having issues.
