### ISSUE TITLE
Mollie.Api.Models.Payment.Locale doesn't support all locales

### ISSUE THREAD

**Issue by gerbenvd** [Viincenttt/MollieApi#26]
Besides the locales mentioned in the Mollie documentation, it has come to my attention that Mollie can also pass in other locales, such as 'uk'. This trips over the class Mollie.Api.Models.Payment.Locale, resulting in the following error message:

Error converting value "uk" to type 'Mollie.Api.Models.Payment.Locale'. Path 'locale', line 1, position 442. ---> System.ArgumentException: Requested value 'uk' was not found.

The cause of this is that not all possible locales are defined in this class: https://github.com/Viincenttt/MollieApi/blob/master/Mollie.Api/Models/Payment/Locale.cs

I talked to Mollie support on the phone stating that if you leave the Locale parameter empty when creating the payment request, Mollie will pass in the users' browser-language when calling the webhook. 

I think that the Locale.cs should be extented so it contains more locales or the locale parameter should be a string so that it more flexible for future locales.

**Comment by Viincenttt** [comment]
I'm not sure I understand. The Locale parameter on PaymentRequest and PaymentResponse is a string for exactly this reason. The Locale values in Locale.cs are just pre-set strings you can use.

**Comment by gerbenvd** [comment]
Aaaah stupid me. I was using an old version (1.3.5) which was still using enums in the Locale. After upgrading to the latest version 1.4 this seems resolved now.

**Comment by Viincenttt** [comment]
No problem :)
