### ISSUE TITLE
Where to pass in accessToken?

### ISSUE THREAD

**Issue by DianaKoenraadt** [Viincenttt/MollieApi#260]
I'm obtaining a token via the Connect API.
How do I use it?
Wherever your docs say `yourApiKey`, should I there pass in the accessToken?

**Comment by Viincenttt** [comment]
Hi @DianaKoenraadt ,

Mollie uses three types of authentication:
- API keys
- Organization access tokens
- App access tokens

You can read more about the different types of authentication in the Mollie documentation: https://docs.mollie.com/overview/authentication

When using this library, you can pass in a api-key, oauth token or access token. Keep in mind that some authentication modes have additional fields, such as profileId and testmode. 

Kind regards,
Vincent

**Comment by Viincenttt** [comment]
Closing the issue. Feel free to leave a comment if this is still an issue, then I will reopen it
