### ISSUE TITLE
Upgrading from 1.5.2 to 2.1.0.9 - Mollie is saying I'm still using V1 endpoint

### ISSUE THREAD

**Issue by ipsisPuckHolshuijsen** [Viincenttt/MollieApi#261]
Hi,

First of all, love this project, has helped me out alot.
I've got a website which had V1.5.2 which I upgraded to 2.1.0.9, but I'm still not seeing paymentmehods like Klarna. Contacted Mollie about it, and they said everything was setup right in the Mollie-account, but that i'm still using their V1 endpoint.

Are there steps I have to take for upgrading? Or am I just doing something wrong?
Hope you can help and if there is information missing, I'm happy to give :)

Thanks!
Kind regards,
Puck

**Comment by Viincenttt** [comment]
Hi @ipsisPuckHolshuijsen ,

Besides updating the NuGet package there are no other steps you have to take to upgrade to v2. Could it be that perhaps you have references to different versions of the NuGet package in your project? 

If you have succesfully upgraded to the latest version of the library, you should be able to access all the functionality of the v2 API, for example: OrderClient or SettlementClient. 

Kind regards,
Vincent

**Comment by ipsisPuckHolshuijsen** [comment]
Hi @Viincenttt ,

Yeah, I have the functionalities of the V2. I can also see the V2 endpoint in the PaymentClient. But at Mollie they say I am still using the V1 API and I don't see the payment methods like Klarna (which is correctly setup and activated in the account at Mollie).

Kind regards,
Puck

**Comment by Viincenttt** [comment]
Hi @ipsisPuckHolshuijsen ,

Just to clarify, which methods are you calling where you are not seeing Klarna? Klarna is only available using the Order API, which is a v2 API. It can not be used with the Payment API. 

See this snippet on the documentation of the Create Payment endpoint on the Mollie API documentation
![image](https://user-images.githubusercontent.com/10780135/163538254-6df63b83-a94a-4bd0-98b6-7dd0c5caacd9.png)

Kind regards,
Vincent

**Comment by ipsisPuckHolshuijsen** [comment]
Oh my god.. thank you! I must've missed that part.
I'm calling the CreatePayment method, which makes sense now that I don't see Klarna.

Kind regards,
Puck

**Comment by ipsisPuckHolshuijsen** [comment]
Yeah, this was my issue.
Thanks!
