### ISSUE TITLE
Subscription API: Reference to a non-shared member requires an object reference.

### ISSUE THREAD

**Issue by neo1992** [Viincenttt/MollieApi#262]
I have this code, but I get this design time error on line `Dim subscriptionResponse As Mollie.Api.Models.Subscription.SubscriptionResponse = Await Mollie.Api.Client.SubscriptionClient.CreateSubscriptionAsync("{customerId}", subscriptionRequest)`

>  Reference to a non-shared member requires an object reference.

    Protected Async Sub StartPayment()
        Dim mollieCurrency As String = "EUR"
        mollieCurrency = Mollie.Api.Models.Currency.EUR

        Dim subscriptionClient As Mollie.Api.Client.Abstract.ISubscriptionClient = New Mollie.Api.Client.SubscriptionClient(ConfigurationManager.AppSettings("mollie_api_testkey"))

        Dim subscriptionRequest As Mollie.Api.Models.Subscription.SubscriptionRequest = New Mollie.Api.Models.Subscription.SubscriptionRequest() With {
        .Amount = New Mollie.Api.Models.Amount(mollieCurrency, "5.00"),
        .Interval = "1 month",
        .Description = "{uniqueIdentifierForSubscription}"
    }
        Dim subscriptionResponse As Mollie.Api.Models.Subscription.SubscriptionResponse = Await Mollie.Api.Client.SubscriptionClient.CreateSubscriptionAsync("{customerId}", subscriptionRequest)

    End Sub

**Comment by Viincenttt** [comment]
I'm glad the issue is resolved. I was afraid I would have to install the VB.NET development tools ;)

**Comment by neo1992** [comment]
LOL. I'm sorry to do this to you, struggling through this myself too :)
Also I'm not sure if you want me to open these questions here or rather on Stackoverflow. But I have another one that relates to the customer API: https://github.com/Viincenttt/MollieApi/issues/263
