### ISSUE TITLE
'ConsumerAccount' is not a member of 'MandateRequest'

### ISSUE THREAD

**Issue by neo1992** [Viincenttt/MollieApi#264]
I believe the documentation here is incorrect: https://github.com/Viincenttt/MollieApi#7-mandate-api
'ConsumerAccount' is not a member of 'MandateRequest'

After inspecting [the code](https://github.com/Viincenttt/MollieApi/blob/development/Mollie.Api/Models/Mandate/MandateRequest.cs) I indeed see no such property. Should documentation be updated to reflect this?

**Comment by Viincenttt** [comment]
Thank you, I'll update the documentation on this. 

If you still want to create a mandate request with a consumer account, you can use the following code:
```
return new SepaDirectDebitMandateRequest() {
                Method = Api.Models.Payment.PaymentMethod.DirectDebit,
                ConsumerName = "John Smit",
                ConsumerAccount = "NL86INGB0002445588"
            };
```
