### ISSUE TITLE
Mollie.Api.Models.Order.OrderPaymentRequest pass array of methods

### ISSUE THREAD

**Issue by DianaKoenraadt** [Viincenttt/MollieApi#266]
The Mollie docs describe that it is possible to pass in an array of methods as well. Currently, only `Method` is implemented. Would be great if this could be added, too.

**Comment by Viincenttt** [comment]
Correct, currently this is only implemented in the `PaymentRequest` class and not in the `OrderPaymentRequest` class . I will add this feature in the upcoming release.

Kind regards,
Vincent

**Comment by DianaKoenraadt** [comment]
Thank you, much appreciated!

**Comment by Viincenttt** [comment]
This issue is now resolved in version 2.1.0.10

**Comment by DianaKoenraadt** [comment]
Awesome, thanks!
