### ISSUE TITLE
Mollie.Api.Models.Order.OrderPaymentRequest missing TestMode parameter

### ISSUE THREAD

**Issue by DianaKoenraadt** [Viincenttt/MollieApi#267]
It seems like there is no 'TestMode' parameter in this request object.

**Comment by Viincenttt** [comment]
Hi Diana,

Thank you for reporting this issue, I've been on holiday, so it's taken a bit longer then usual for me to reply. 

You are correct, the parameter is missing. I have added a commit to fix this. I will release it early next week :)

Kind regards,
Vincent

**Comment by DianaKoenraadt** [comment]
No problem, glad to hear back from you. Looking forward to the next release, great!

**Comment by Viincenttt** [comment]
This issue is now resolved in version 2.1.0.10
