### ISSUE TITLE
Profiles API categoryCode deprecated

### ISSUE THREAD

**Issue by DianaKoenraadt** [Viincenttt/MollieApi#269]
Hi, I just wanted to let you know that the `categoryCode` field in the Create Profile call is deprecated.
It will be replaced by `businessCategory`. Please refer to https://docs.mollie.com/reference/v2/profiles-api/create-profile

**Comment by Viincenttt** [comment]
The issue has been solved in the development branch. The CategoryCode property will be marked as deprecated (obsolete) and I have added support for the BusinessCategory property

**Comment by Viincenttt** [comment]
This is now live in version 2.1.0.11
