### ISSUE TITLE
Mollie in PCL project (xamarin forms and Prism)

### ISSUE THREAD

**Issue by Deacom** [Viincenttt/MollieApi#27]
I'm not able to add Mollie.Api to a portable Class Library.
I'm just a starting programmer so i could be that i just do not know how.

Is there a way to install the nuget in pcl? will this be an option in the future?

kind regards,
Daniel Commandeur

**Comment by Viincenttt** [comment]
Hi Deacom,

I have released a new version of the Mollie API and it is now a .NET standard project, which should hopefully resolve your issues. 

Kind regards,
Vincent
