### ISSUE TITLE
Could you expose profileId parameter in GetAllPaymentMethodListAsync?

### ISSUE THREAD

**Issue by DianaKoenraadt** [Viincenttt/MollieApi#270]
When using Mollie Connect, this parameter must be supplied by caller. Could you expose it please?

**Comment by Viincenttt** [comment]
Thanks for the headsup. I have added support for the profileId parameter. It will be added to the next release.

**Comment by DianaKoenraadt** [comment]
Awesome, thanks. Oh, I have to mention, I asked you about the testmode parameter: I haven't been able to use your latest release yet because there was some testmode parameter still missing. Sorry I didn't report back earlier. If you want I'll inspect which one it is in the coming week.

**Comment by Viincenttt** [comment]
Hi @DianaKoenraadt ,

Yes, please let me know if you encounter any missing parameters. Feel free to open a new issue.

Kind regards,
Vincent

**Comment by Viincenttt** [comment]
This is now live in version 2.1.0.11
