### ISSUE TITLE
Missing Testmode parameter in various clients

### ISSUE THREAD

**Issue by DianaKoenraadt** [Viincenttt/MollieApi#272]
As discussed, I've looked at my code and am reporting back to let you know which calls still lack the testmode parameter.
Currently, I'm manually implementing `IShipmentClient` and `IOrderClient`, because the testmode parameter is missing in the following five calls:

- `ShipmentClient.CreateShipmentAsync`
- `OrderClient.GetOrderAsync`
- `OrderClient.CancelOrderAsync`
- `OrderClient.CreateOrderPaymentAsync`
- `OrderClient.CreateOrderRefundAsync`

I haven't checked other clients or calls, these are only the five that I've encountered.
Kind regards

**Comment by DianaKoenraadt** [comment]
Oh, found another one in PaymentClient:

- `PaymentMethodClient.GetPaymentMethodListAsync`

**Comment by Viincenttt** [comment]
Thank you, it seems I have forgotten to add for a lot of the API endpoints. In addition to the endpoints you mentioned above, I'll check all endpoints to make sure we don't miss any.

**Comment by DianaKoenraadt** [comment]
Do you have a release date in mind for the new version? We're working our way toward a release of our webshop functionality and we're hoping to release that in rwo weeks.

(I can always resort to temporarily checking out your code base, because all I really need now is that profileId parameter, which you mentioned you implemented already. But if I can use the new NuGet package that would be preferable of course.)

**Comment by Viincenttt** [comment]
If you only need the `profileId` parameter I can create a new NuGet package tonight. If you also need the testmode parameter thats missing in a lot of places, it will take longer (next weekend or the weekend after that). Let me know if you need a new release with the `profileId` parameter :)

**Comment by DianaKoenraadt** [comment]
Thanks for the offer! I've decided that since I'm currently overriding some of your classes anyway, I'll do that for the `profileId` parameter too, for now. As soon as the new NuGet package is there, I'll upgrade everything in one go :) So no worries, this way I'm not blocked and you can do it whenever suits you best.

**Comment by Viincenttt** [comment]
I have compared the API reference with the current code and found many more API clients and methods that are currently missing the `testmode` parameter. The full list is: 

PaymentClient - Cancel payment
CapturesClient - Get capture
CapturesClient - Get captures list
OrderClient - Update order
OrderClient - Update order lines
OrderClient - Cancel order
OrderClient - Get order list
OrderClient - Cancel order lines
OrderClient - Create order refund
OrderClient - Get order refund list
CustomerClient - Create customer
CustomerClient - Get customer
CustomerClient - Get customer list
CustomerClient - Get customer payment list (also missing profileId)
MandateClient - Get mandate
MandateClient - Get mandate list
MandateClient - Create mandate
MandateClient - Revoke mandate
SubscriptionClient - Get customer subscription list
SubscriptionClient - Get all subscription list
SubscriptionClient - Get subscription
SubscriptionClient - Create subscription
SubscriptionClient - Update subscription
SubscriptionClient - Cancel subscription
SubscriptionClient - Get subscription payment list

Looks like I have my work cut out for me. I'll focus on the most used clients and methods first.

**Comment by Viincenttt** [comment]
This is now live in version 2.1.0.11

**Comment by DianaKoenraadt** [comment]
Wow, that was fast. Great job, thanks!

**Comment by whats-it-nl** [comment]
Small addition:

- [ ]  chargebacksClient.GetChargebackAsync() (missing Testmode parameter)
- [ ] subscriptionRequest (profileId missing)

Will do some more testing next week on our dev environment
