### ISSUE TITLE
Mollie.Api.Client.MollieApiException: Unprocessable Entity - Cannot accept both `businessCategory` and `categoryCode` parameters. Please only use the `businessCategory` parameter.

### ISSUE THREAD

**Issue by DianaKoenraadt** [Viincenttt/MollieApi#273]
I'm afraid something isn't quite right with the `CreateProfileAsync` call.

Mollie reports the error `Mollie.Api.Client.MollieApiException: Unprocessable Entity - Cannot accept both `businessCategory` and `categoryCode` parameters. Please only use the `businessCategory` parameter.`.

**Comment by Viincenttt** [comment]
Hi Diana,

Thank you for reporting the issue. This issue is now solved in version 2.1.0.12
