### ISSUE TITLE
Product afbeelding mist

### ISSUE THREAD

**Issue by MartijnDijkgraaf** [Viincenttt/MollieApi#275]
Hey Vincent,

Ten eerste bedankt voor deze package!

Ik heb een vraag, ik schiet een order in met verschillende producten, waarbij ik ook de productImage inschiet.
Nu is het zo dat ik bij het ophalen van de order, deze afbeelding niet mee krijg in het request. Ik denk dat er ergens wat mis gaat in de package.

Ik zie ook in de Mollie documentatie dat de link in de _links parameter van de line moet zitten, maar deze _link parameter bestaat niet in het request wat ik via de package terug krijg, misschien is er iets veranderd?

Alvast bedankt voor je antwoord, 

Als ik ergens mee kan helpen dan hoor ik het graag.

Groetjes, 
Martijn

**Comment by Viincenttt** [comment]
Hi Martijn,

Thank you for reporting this issue. It would seem I have forgotten to add support for the `_links` parameter in the `OrderLineResponse` class. I have just added a commit that resolves this issue. I will probably release a new version of the library this weekend to resolve the issue. 

Kind regards,
Vincent

**Comment by MartijnDijkgraaf** [comment]
Thanks for the reply, I’ll wait for the new version.

p.s. next time I will create a ticket in English

**Comment by Viincenttt** [comment]
Hi Martijn,

No problem, I like to keep the communication in english, so readers that do not speak english are also able to understand the conversation :)

I have just released version 2.1.0.13 of the library in which the above issue has been resolved. If you update to the latest NuGet package, you should be able to access the product and image URL's for each order line using the `OrderLineResponse` -> `Links` property.

Kind regards,
Vincent
