### ISSUE TITLE
Missing metadata in order line

### ISSUE THREAD

**Issue by MartijnDijkgraaf** [Viincenttt/MollieApi#276]
Hey Vincent,

With your latest patch you removed the access to the [Metadata](https://github.com/Viincenttt/MollieApi/blob/e87b6323a3bd0cf4cbe800997bdf5bc352d22255/Mollie.Api/Models/Order/Request/OrderLineRequest.cs#L76) property.

**Comment by Viincenttt** [comment]
Hi Martijn,

You are right, it seems I have made a mistake when I made the change to have the `OrderLineResponse` class no longer inherit from the `OrderLineRequest` class. 

I have merged your PR and will release a new version right away.

Kind regards,
Vincent

**Comment by Viincenttt** [comment]
I have uploaded a new version to NuGet. It may take up to one hour for NuGet to index and publish the new version.
