### ISSUE TITLE
Add support for strong name reference

### ISSUE THREAD

**Issue by maykSVK** [Viincenttt/MollieApi#278]
Hi, I would like to ask, if you are planning add support for strong name? Now when I try to use your library, I got errors:
Referenced assembly 'Mollie.Api, Version=2.1.0.14, Culture=neutral, PublicKeyToken=null' does not have a strong name.

Sure I can sign it on my side, but it feels like hack and any update to this library will break it. Can you help me with that?

**Comment by Viincenttt** [comment]
Hi @maykSVK ,

Good idea! I do not use strong named projects myself, so I never encountered this error. I do understand it can be problematic if you are working in an environment that enforces strong names. I'll look into this.

Kind regards,
Vincent

**Comment by maykSVK** [comment]
Hi @Viincenttt,
thank you for looking into this. Can you give me an rough estimation, where it will be?

Thank you.

**Comment by Viincenttt** [comment]
Rough estimate is somewhere between tomorrow and a few weeks

**Comment by maykSVK** [comment]
Hi Vincent, 
I am just curious, whether this feature were implemented in new version and if not, then I would like to ask, if it will be or not? I have tries it and I am still getting:
Warning	CS8002	Referenced assembly 'Mollie.Api, Version=2.1.0.15, Culture=neutral, PublicKeyToken=null' does not have a strong name.
