### ISSUE TITLE
GiftcardPaymentResponse seems to be missing Details property

### ISSUE THREAD

**Issue by rbaarda** [Viincenttt/MollieApi#279]
It seems that most specific payment response classes have a Details property containing specific information about that type of payment. However in case of GiftcardPaymentResponse these properties seem to be directly located in the specific GiftcardPaymentResponse instead of in a Details property. The giftcard specific properties seem to be always null on my end. My guess is deserializing the response doesn't fill the specific properties.

The documentation at https://docs.mollie.com/reference/v2/payments-api/get-payment#payment-method-specific-response-parameters seems to be suggesting that the giftcard specific properties reside inside a details property.

This is how I try to get the specific information:
```
var result = await _paymentClient.GetPaymentAsync(paymentId, includeRemainderDetails: true);
if (result is GiftcardPaymentResponse giftCardResult)
{
   // giftCardResult specific properties are null here.
}
```

**Comment by Viincenttt** [comment]
Hi @rbaarda ,

Thanks for reporting this issue. I've looked at the Mollie documentation and it was indeed missing the details property. I've added a commit to fix this issue. 

Kind regards,
Vincent

**Comment by Viincenttt** [comment]
This is now live in version 2.1.0.15: https://github.com/Viincenttt/MollieApi/releases/tag/2.1.0.15
