### ISSUE TITLE
Missing Revoking of a Mandate in MandateClient

### ISSUE THREAD

**Issue by owingruters** [Viincenttt/MollieApi#28]
Hi Vincent,

In the Mandateclient, there is only support for retrieval of a mandate and a mandatelist. 
When deleting a subscription of a recurring payment, I think the mandate should also be deleted. Can you add the revocation method?

Cheers!
Owin

(sorry if this issue is created twice, network failure...)

**Comment by Viincenttt** [comment]
Hi owingruters,

Today I have released a new version and this API call is now included. 

Kind regards,
Vincent

**Comment by owingruters** [comment]
Thats fantastic!!
