### ISSUE TITLE
[JsonSerializerSettings] Unprocessable Entity Non-existent body parameter "$id"

### ISSUE THREAD

**Issue by stddd** [Viincenttt/MollieApi#280]
Hello, 

At first thanks for this library,

When i tried to implement the library in my existing net core 3.1 project,
the response of mollie was always : `"{\"status\":422,\"title\":\"Unprocessable Entity\",\"detail\":\"Non-existent body parameter \\\"$id\\\" for this API call. Did you mean: \\\"name\\\"?\",\"field\":\"$id\",\"_links\":{\"documentation\":{\"href\":\"https://docs.mollie.com/overview/handling-errors\",\"type\":\"text/html\"}}}"`

after implementing your project as a ref, it seems than your JsonConverterService doesn't implement a PreserveReferencesHandling = PreserveReferencesHandling.None, so if the base project not implement a JsonSerializeSettings with this parameter, the id is added by default to the serialize : 
![image](https://user-images.githubusercontent.com/7623789/199051605-5c7f426e-e1b3-4e51-8c77-e19d7bcc9ea8.png)

adding the PreserveReferencesHandling to the JsonConverterService did the job : 
![image](https://user-images.githubusercontent.com/7623789/199051805-cb7220f9-8b2c-4f96-b4d4-750fa624d565.png)

Have a good day !

**Comment by Viincenttt** [comment]
Hi @stddd ,

Thanks for the feedback, I haven't encountered this issue before. Could you tell me a little bit more on how to replicate this issue? I would have thought that if this was an issue, it should also occur when I run the integration tests of the project.

If it wouldn't be too much trouble, could you a sample on how to replicate this issue and attach it?

Kind regards,
Vincent

**Comment by stddd** [comment]
After reviewing why this is happen only in my API,
I forgot my own implementation of JsonSerializerSettings for the need of the project
so in my startup.cs ConfigureServices : 
`JsonConvert.DefaultSettings = () => new JsonSerializerSettings
            {
                Formatting = Formatting.None,
                NullValueHandling = NullValueHandling.Ignore,
                TypeNameHandling = TypeNameHandling.None,
                ContractResolver = new CamelCasePropertyNamesContractResolver(),
                ReferenceLoopHandling = ReferenceLoopHandling.Ignore,
                PreserveReferencesHandling = PreserveReferencesHandling.Objects
            };`

when we try to call : 
![image](https://user-images.githubusercontent.com/7623789/199449077-829807c6-732a-4f9e-ae4e-c01907cf6808.png)

The problem occurs.

**Comment by Viincenttt** [comment]
Hi @stddd ,

Thanks for the code sample. I've added a commit to fix this.

Kind regards,
Vincent
