### ISSUE TITLE
C# SDK does not allow me to fetch profile with Oauth access token

### ISSUE THREAD

**Issue by SDanDyS** [Viincenttt/MollieApi#281]
I am implementing Oauth2 and wish to retrieve a profileId, which should be used for payments. However when trying to use Oauth to retrieve a profileId I get the following error _"MollieApiException: Forbidden - This API endpoint is only available with an API key and cannot be accessed with an OAuth access token."_. In the PHP SDK it's possible to retrieve profiles (including the current profile) through Oauth. Is this also possible within the C# SDK, or hasn't this been implemented yet?
The implementation of the retrieval of the profileId is done like this:

```            
IProfileClient client = new ProfileClient(this.tokenResponse.AccessToken);
ProfileResponse profileResponse = await client.GetCurrentProfileAsync();
this.profileResponse = profileResponse;
```

am I missing something?

**Comment by Viincenttt** [comment]
Hmmm.... I'm not sure. Looking at the exception it does seem to come from the Mollie API. I'll have to do some investigating on this. I'll come back on this.

**Comment by Viincenttt** [comment]
Looking at the API documentation, the endpoint you are calling ("Get current profile") does not support OAuth tokens:
https://docs.mollie.com/reference/v2/profiles-api/get-profile-me

The "Get profile" endpoint does support this:
https://docs.mollie.com/reference/v2/profiles-api/get-profile

**Comment by SDanDyS** [comment]
Well, if only the API key works for a profile, then  I doubt the PHP library did this as well. I must've been thinking of something else. But to be sure (debugger already somewhat confirmed this): I can pass an access token to the PaymentClient object and it'll internally handle it, correct?

**Comment by Viincenttt** [comment]
Jep, that should totally work :)

I'm closing this issue for now. Feel free to reply or open a new issue if you encounter any problems :)

**Comment by joshua-classen** [comment]
Hey is this nuget package outdated? On the mollie api reference they say you need an access token now. It feels also far more natural to do it with an access token. I am building a SaaS where many People connect their mollie account with the platform mollie account. So how could i get the profileId from a specific user with just the api key? its now possible. You cannot initialize the ProfileApi with an access token right now: https://github.com/Viincenttt/MollieApi/wiki/11.-Profile-Api

<img width="917" height="298" alt="Image" src="https://github.com/user-attachments/assets/2be985bf-304c-4219-be4d-b20589fcea8a" />
