### ISSUE TITLE
Connect API and Split Payments

### ISSUE THREAD

**Issue by DiedrikDM** [Viincenttt/MollieApi#288]
Hi!

There's a closed beta currently for supporting Split Payments by adding a ```routing``` parameter to the PaymentRequest. See these reference in the Mollie documentation: https://docs.mollie.com/reference/v2/payments-api/create-payment#mollie-connect-parameters and https://docs.mollie.com/connect/splitting-payments .
Are you thinking about adding this property or will this be something for the distant future, when it becomes publicly available?

Thanks for the info and the effort in the library!

**Comment by Viincenttt** [comment]
Hi @DiedrikDM ,

Yes, I'm aware of the split payment feature, but the library doesn't support this at the moment. I am planning to add support for it, but I do not have a timeline available at the moment.

I'll keep this issue open until support is added.

Kind regards,
Vincent

**Comment by Viincenttt** [comment]
This is now live in 2.2.0.2

Thanks again for the pull request! :D
