### ISSUE TITLE
Cannot compile the solution

### ISSUE THREAD

**Issue by marcverkade** [Viincenttt/MollieApi#29]
Hai, no clue if this is the right place to add comments / issues.

I downloaded the solution, loaded it into VS2015, rebuild the solution and get several errors.
Why?

Severity	Code	Description	Project	File	Line	Source	Suppression State
Error	CS1061	'BaseMollieApiTestClass' does not contain a definition for 'ApiTestKey' and no extension method 'ApiTestKey' accepting a first argument of type 'BaseMollieApiTestClass' could be found (are you missing a using directive or an assembly reference?)	Mollie.Tests.Integration	D:\Develop\DotNet35\MollieApi-master\Mollie.Tests.Integration\Framework\BaseMollieApiTestClass.cs	22	IntelliSense	Active

Severity	Code	Description	Project	File	Line	Source	Suppression State
Error	CS0121	The call is ambiguous between the following methods or properties: 'Mollie.Api.Extensions.RestSharpExtensionMethods.IsScuccessStatusCode(System.Net.HttpStatusCode)' and 'Mollie.Api.Extensions.RestSharpExtensionMethods.IsScuccessStatusCode(System.Net.HttpStatusCode)'	Mollie.Api	D:\Develop\DotNet35\MollieApi-master\Mollie.Api\Extensions\RestSharpExtensionMethods.cs	7	IntelliSense	Active

Severity	Code	Description	Project	File	Line	Source	Suppression State
Error	CS0121	The call is ambiguous between the following methods or properties: 'Mollie.Api.Extensions.RestSharpExtensionMethods.IsSuccessful(RestSharp.IRestResponse)' and 'Mollie.Api.Extensions.RestSharpExtensionMethods.IsSuccessful(RestSharp.IRestResponse)'	Mollie.Api	D:\Develop\DotNet35\MollieApi-master\Mollie.Api\Client\BaseMollieClient.cs	66	IntelliSense	Active

p.s. If there is some forum, please add details so I can ask questions overthere while implementing these classes.

Regards, Marc

**Comment by marcverkade** [comment]
Hmm, the API and samples are in DotNet 4.. Our solution is in 3.5 and we cannot migrate that easy to 4... Do I have to write my own routines or can I use these DotNet 4 dll somehow?

**Comment by Viincenttt** [comment]
Hi Marc,

Unfortunatly .NET 3.5 is not supported at the moment. 

Kind regards,
Vincent
