### ISSUE TITLE
Missing includeWallets argument for PaymentMethodClient

### ISSUE THREAD

**Issue by Flo301** [Viincenttt/MollieApi#291]
https://docs.mollie.com/reference/v2/methods-api/list-methods#parameters

**Comment by Viincenttt** [comment]
Hi @Flo301 

Thanks for reporting the missing parameter. I'll make sure to add it in the next release :)

Kind regards,
Vincent

**Comment by Viincenttt** [comment]
I've added the code for the optional includeWallets parameter. It will be in the next release.

**Comment by Viincenttt** [comment]
This is now live in 2.2.0.3

**Comment by Flo301** [comment]
Thanks
