### ISSUE TITLE
expiresAt parameter

### ISSUE THREAD

**Issue by JvdGraaff** [Viincenttt/MollieApi#294]
In the documentation it says that in de Orders API there is a parameter "expiresAt". But when I look for that parameter in the "OrderRequest" object the parameter is not there. How can I set the parameter when it not exposed?

**Comment by Viincenttt** [comment]
Hi @JvdGraaff ,

I'm not sure what you mean. When I check the code the parameter is present: https://github.com/Viincenttt/MollieApi/blob/development/Mollie.Api/Models/Order/Request/OrderRequest.cs#L120

Kind regards,
Vincent

**Comment by JvdGraaff** [comment]
Hi Vincent,

I don’t see the property presented by Intellisense in my code.

***@***.***

The _OrderRequest object is a Mollie.Models.Order.OrderRequest object but when I enter the “.” After “_OrderRequest” the “ExpiresAt” property is not presented.
Am I using the wrong object?

Regards,
Jeroen

Van: Vincent Kok ***@***.***>
Verzonden: donderdag 2 februari 2023 18:28
Aan: Viincenttt/MollieApi ***@***.***>
CC: Jeroen van der Graaff ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [Viincenttt/MollieApi] expiresAt parameter (Issue #294)


Hi @JvdGraaff<https://github.com/JvdGraaff> ,

I'm not sure what you mean. When I check the code the parameter is present: https://github.com/Viincenttt/MollieApi/blob/development/Mollie.Api/Models/Order/Request/OrderRequest.cs#L120

Kind regards,
Vincent

**Comment by Viincenttt** [comment]
Hi @JvdGraaff 

Are you using the latest version of the library?

Kind regards,
Vincent

**Comment by JvdGraaff** [comment]
Vincent,

I use:

***@***.***

From the Mollie website.

Jeroen

Van: Vincent Kok ***@***.***>
Verzonden: maandag 6 februari 2023 09:42
Aan: Viincenttt/MollieApi ***@***.***>
CC: Jeroen van der Graaff ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [Viincenttt/MollieApi] expiresAt parameter (Issue #294)


Hi @JvdGraaff<https://github.com/JvdGraaff>

Are you using the latest version of the library?

Kind regards,
Vincent

**Comment by Viincenttt** [comment]
What do you mean? That is not a version number

**Comment by JvdGraaff** [comment]
Vincent,

Mollie.dll is version 3.0.0
Mollie.Api.dll is version2.2.0.3

Jeroen

Van: Vincent Kok ***@***.***>
Verzonden: maandag 6 februari 2023 13:16
Aan: Viincenttt/MollieApi ***@***.***>
CC: Jeroen van der Graaff ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [Viincenttt/MollieApi] expiresAt parameter (Issue #294)


What do you mean? That is not a version number

**Comment by Viincenttt** [comment]
Mollie.dll is not something that is published by this library. Mollie.Api.dll 2.2.0.3 is the latest version. 

I'm afraid I'm not able to help you. If I install the package in a new project, the `ExpiresAt` is available. So it seems it's an issue on your local machine.
