### ISSUE TITLE
New Package for customer/mandates

### ISSUE THREAD

**Issue by owingruters** [Viincenttt/MollieApi#3]
Hi Vincent,

Great work you are doing, also by including customer and mandates. Will you also create a new NuGet package for this update?
Hope you can answer this, otherwise I'll use the code itself, but makes updating less handy...

Regards,
Owin

**Comment by Viincenttt** [comment]
Hi Owin,

My apologies for the delay. I have created a new NuGet package for this update. Version 1.3.2. 

Regards,
Vincent

**Comment by owingruters** [comment]
That's great! Kudo's
