### ISSUE TITLE
Extend CustomerResponse with payment methods

### ISSUE THREAD

**Issue by PostbuzzAndriy** [Viincenttt/MollieApi#30]
Hello, Vincent.
Wouldn't it be so difficult for you to extend this response type with the list of the last used payment methods as Mollie provides?
"recentlyUsedMethods": []

**Comment by Viincenttt** [comment]
Hi gerwin3. 

I have added the RecentlyUsedMethods property in version 1.4.3 of the API, which is now available on NuGet. 

Kind regards,
Vincent

**Comment by PostbuzzAndriy** [comment]
Thanks a lot!
