### ISSUE TITLE
IPaymentClient should inherit from IDisposable

### ISSUE THREAD

**Issue by woutware** [Viincenttt/MollieApi#319]
As some IPaymentClient implementations internally use HttpClient objects, which are disposable, the IPaymentClient itself should also be disposable. So ideally the IPaymentClient interface inherits from IDisposable. If not all implementations are disposable, you could make individual implementations implement IDisposable, but I think more user friendly would be to let the interface inherit it.

Also you might need to check if the HttpClient was passed to the payment client from the outside, in which case the payment client is not the owner of the http client, and therefore should not dispose it. But if the HttpClient was created by the payment client, it should dispose of it.

**Comment by Viincenttt** [comment]
Hi @woutware ,

Good idea, I agree with your suggestion. The recommended way to use the Mollie .NET client is to use the recently introduced dependency injection extension method, as described in the documentation:
https://github.com/Viincenttt/MollieApi#dependency-injection 

In case someone is not using dependency injection and is using the constructor variant where no HttpClient instance is provided, I'll see if I can add some code to dispose the HttpClient instance that is created by the Mollie API classes.

Kind regards,
Vincent

**Comment by Viincenttt** [comment]
This is now done and will be released in the next version

**Comment by woutware** [comment]
Looks great Vincent!

**Comment by Viincenttt** [comment]
This is now live in 3.1.0.0
https://github.com/Viincenttt/MollieApi/releases/tag/3.1.0.0

**Comment by Viincenttt** [comment]
Thanks for the feedback @woutware , I really appreciate it! :) 

I'll update the documentation to make this part a bit more clear

**Comment by woutware** [comment]
The wording is much better now! And the checkout url paragraph looks good too, overall great job on the documentation!
