### ISSUE TITLE
Support for get payment refund 

### ISSUE THREAD

**Issue by sebbertho** [Viincenttt/MollieApi#321]
I would like to access the get-payment-refund call: https://docs.mollie.com/reference/v2/refunds-api/get-payment-refund. Do I miss something or shall I implement a suggestion and issue a pull request?

**Comment by Viincenttt** [comment]
Hi @sebbertho ,

This method is available in the `RefundClient`: https://github.com/Viincenttt/MollieApi/blob/da209ccbdc098168838e59092281129a9e67ec2a/src/Mollie.Api/Client/RefundClient.cs#L48

``` C#
public async Task<RefundResponse> GetRefundAsync(string paymentId, string refundId, bool testmode = false) {
    this.ValidateRequiredUrlParameter(nameof(paymentId), paymentId);
    this.ValidateRequiredUrlParameter(nameof(refundId), refundId);
    var queryParameters = this.BuildQueryParameters(testmode: testmode);
    return await this.GetAsync<RefundResponse>($"payments/{paymentId}/refunds/{refundId}{queryParameters.ToQueryString()}").ConfigureAwait(false);
}
```

Let me know if you have any question about this method.

Kind regards,
Vincent

**Comment by Viincenttt** [comment]
Closing this for now, let me know if you need any further help regarding this issue
