### ISSUE TITLE
Pagination on GetChargebacksListAsync

### ISSUE THREAD

**Issue by sebbertho** [Viincenttt/MollieApi#322]
I would like to use pagination to get all results in GetChragebacksListAsync. Do I miss something or shall I write an implementation and file a pull request?

**Comment by Viincenttt** [comment]
Hi @sebbertho 

Nice catch! You meant that the ChargebackClient does not have a method to fetch the Next/Previous items right? I have just created a commit to add this functionality.

I also went through all the other clients to see which ones had this functionality and which clients were also missing it:
- [ ] BalanceClient
- [ ] CaptureClient
- [x] ChargebacksClient
- [x] CustomerClient
- [ ] InvoicesClient
- [x] MandateClient
- [x] OrderClient
- [ ] OrganizationsClient
- [x] PaymentClient
- [x] PaymentLinkClient
- [ ] ProfileClient
- [x] RefundClient
- [x] SettlementsClient
- [ ] ShipmentClient
- [x] SubscriptionClient
- [x] TerminalClient

I'll make sure to add these methods to the other clients as well.

Kind regards
Vincent

**Comment by Viincenttt** [comment]
This is now done and will be released in the next version

**Comment by Viincenttt** [comment]
This is now live in 3.1.0.0
https://github.com/Viincenttt/MollieApi/releases/tag/3.1.0.0
