### ISSUE TITLE
Wallet API support

### ISSUE THREAD

**Issue by andrewmarkham** [Viincenttt/MollieApi#326]
Hi,

Is the Wallets API supported?  I am looking to create an apple payment session>

https://docs.mollie.com/reference/v2/wallets-api/request-apple-pay-payment-session

**Comment by Viincenttt** [comment]
Hi @andrewmarkham ,

I've added support for the Wallet API in version 3.3 of the NuGet package. Let me know if you encounter any issues with this new functionality.

Kind regards,
Vincent
