### ISSUE TITLE
NuGet package error

### ISSUE THREAD

**Issue by synercoder** [Viincenttt/MollieApi#34]
I got a problem with the package, NuGet specifices that the dependency is the following:

> Newtonsoft.Json (>= 8.0.2)

When installed it upgraded our Newtonsoft.Json to version 8.0.2 (as needed) (from 6.0.0). But when run it gave an error that Newtonsoft.Json 10.0.3 dll could not be found.

I looked at your github and saw that you use 10.0.3 so I would suggest you to update your nuspec file (could not find on github) to include the same reference.

**Comment by Viincenttt** [comment]
Hi Synercoder,

Thanks for letting me know. I will solve this as soon as possible. 

Kind regards,
Vincent

**Comment by Viincenttt** [comment]
Hi Synercoder,

I have just released a new NuGet package with the correct Newtonsoft.Json dependencies. 

Kind regards,
Vincent
