### ISSUE TITLE
Add an .editorconfig file to help maintain styling

### ISSUE THREAD

**Issue by synercoder** [Viincenttt/MollieApi#355]
I opened a [quick PR today](https://github.com/Viincenttt/MollieApi/pull/354) to fix a issue I noticed in the library. But my PR needed a couple extra commits to fix styling issues that my VS wanted to apply to the code. To avoid these kind of style issues, might I suggest [creating an export of your Visual Studio settings/preferences into an .editorconfig file](https://learn.microsoft.com/en-us/visualstudio/ide/create-portable-custom-editor-options?view=vs-2022#other-ways-to-add-an-editorconfig-file), and include it in the root of your repo? That way other contributor automatically write code in your preferred style.

**Comment by Viincenttt** [comment]
Good idea!

**Comment by Viincenttt** [comment]
I've added an editorconfig, thanks for the suggestion. During this month I'll go through the existing code and fix consistency issues where needed.
