### ISSUE TITLE
Error: Unknown http exception occured with status code: 0.

### ISSUE THREAD

**Issue by pabloesp** [Viincenttt/MollieApi#36]
Hi Viicenttt,

We are using your API and sometimes we receive strange errors when calling GetPaymentAsync method to validate a payment. 
We are logging exceptions and this is the error we get:

Error: Unknown http exception occured with status code: 0.

We contacted Mollie support but they don't give us any info about it.
Can you help us with this issue.

Regards, Pablo

**Comment by Viincenttt** [comment]
Hi Pablo,

That's odd. The GetPayment method requires an id. Are you able to reproduce the issue multiple times using the same id? If you can reproduce the issue, you can inspect the resultcontent in the ProcessHttpResponseMessage of the BaseMollieClient class. 

Please let me know when you have the results. 

Kind regards,
Vincent

**Comment by pabloesp** [comment]
Hi Vincent,

 

Thank you for your advice. 

We are not using the last version of the API because we did the implementation a year ago. 

We have checked latest version and the Newtonsoft.Json dependency is a problem for our proyect, because we have dependencies to v.8 and your latest versions points to v.10.

This is in a production environment right now with a high volume of use (20 payments/day) so is not the right moment for testing ;) Is a contest that will be finished in 15-20 days.

So in that scenario, we cannot do a complete debug of this method, without making lot of changes and taking some risks. We can only place GetPayment method in try/catch and log the exception.

 

The working of Mollie IPN is very strange, because for some transactions we receive only one post request to confirm the payment, and for others we receive this confirmation 4 or 5 times, with the same transaction id.

 

We have implemented a workaround consisting in when we receive this exception, retry the call. We did this change 3 days ago, and this case happened 4 times (for 100 payments), but this 4 times, the second call returned OK, so we could confirm the transaction.

 

I guess this error may be due to any network issue or something strange, because with a retry which is done in miliseconds, the response is OK.

 

What we are going to do is wait until the contest is finished, and then try to implement latest version in test environment, and do more tests.

 

Regards,

Pablo.

 

De: Vincent Kok [mailto:notifications@github.com] 
Enviado el: martes, 26 de septiembre de 2017 19:06
Para: Viincenttt/MollieApi <MollieApi@noreply.github.com>
CC: pabloesp <pablo.espada@esbupa.com>; Author <author@noreply.github.com>
Asunto: Re: [Viincenttt/MollieApi] Error: Unknown http exception occured with status code: 0. (#36)

 

Hi Pablo,

That's odd. The GetPayment method requires an id. Are you able to reproduce the issue multiple times using the same id? If you can reproduce the issue, you can inspect the resultcontent in the ProcessHttpResponseMessage of the BaseMollieClient class.

Please let me know when you have the results.

Kind regards,
Vincent

**Comment by Viincenttt** [comment]
Hi Pablo,

Very strange that the second requests does work! I'm eager to find out whether or not installing the latest version of the library fixes this issue.

**Comment by pabloesp** [comment]
Hi Vincent,

 

I guess is a temporary network or Mollie server problem. 

I write to you when we implement latest version.

 

Regards.

Pablo.

 

De: Vincent Kok [mailto:notifications@github.com] 
Enviado el: jueves, 28 de septiembre de 2017 17:04
Para: Viincenttt/MollieApi <MollieApi@noreply.github.com>
CC: pabloesp <pablo.espada@esbupa.com>; Author <author@noreply.github.com>
Asunto: Re: [Viincenttt/MollieApi] Error: Unknown http exception occured with status code: 0. (#36)

 

Hi Pablo,

Very strange that the second requests does work! I'm eager to find out whether or not installing the latest version of the library fixes this issue.

**Comment by Viincenttt** [comment]
Hi Pablo,

Any update? 

Kind regards,
Vincent

**Comment by pabloesp** [comment]
Hi Vincent,

 

No updates. We are working Ok with the “second request” implementation, after receiving http errors.

For the next context (in a few months), we will try to implement your latest version of the API.

 

Regards.

Pablo.

 


Pablo Espada Bueno
 <mailto:pablo.espada@esbupa.com> pablo.espada@esbupa.com
Tlf: 902 05 04 60 - 927 10 70 88
Móvil: 615 15 36 01
 <http://www.esbupa.com/> www.esbupa.com 

****************AVISO LEGAL**************** 

Este mensaje es privado y confidencial y solamente para la persona a la que va dirigido. Si usted ha recibido este mensaje por error, no debe revelar, copiar, distribuir o usarlo en ningún sentido. Le rogamos lo comunique al remitente y borre dicho mensaje y cualquier documento adjunto que pudiera contener. No hay renuncia a la confidencialidad ni a ningún privilegio por causa de transmisión errónea o mal funcionamiento.

 

De: Vincent Kok [mailto:notifications@github.com] 
Enviado el: jueves, 12 de octubre de 2017 16:43
Para: Viincenttt/MollieApi <MollieApi@noreply.github.com>
CC: pabloesp <pablo.espada@esbupa.com>; Author <author@noreply.github.com>
Asunto: Re: [Viincenttt/MollieApi] Error: Unknown http exception occured with status code: 0. (#36)

 

Hi Pablo,

Any update?

Kind regards,
Vincent

**Comment by Viincenttt** [comment]
Closed untill more information is given. Please open a new bug report if the issue is still present in the latest version.
