### ISSUE TITLE
Support for Lines in CreatePayment

### ISSUE THREAD

**Issue by martijnmelchers** [Viincenttt/MollieApi#368]
Any plans to add support for lines in the upcoming releases?

https://docs.mollie.com/reference/create-payment
![chrome_ng2BAYlk6k](https://github.com/Viincenttt/MollieApi/assets/6060006/6c02ec8d-a980-400f-998f-c7e170f4a662)

**Comment by Viincenttt** [comment]
Yes, I saw the announcement for this on the Mollie developer Discord. I plan to pick this up asap.

**Comment by Viincenttt** [comment]
I've just merged the required changes to support payment lines to the development branch: https://github.com/Viincenttt/MollieApi/pull/370

I'll release a new version of this within a week

**Comment by Viincenttt** [comment]
Hi @martijnmelchers 

This change is now live in version 4.1.0.0 of the NuGet package. Let me know if you have any feedback.

Kind regards,
Vincent
