### ISSUE TITLE
Veranderingen in 4.0.0 versie.

### ISSUE THREAD

**Issue by henkkelder** [Viincenttt/MollieApi#369]
Vandaag heb ik mijn .NET 4.81 applicatie geupdate naar de laastste versie (4.0.0).

ZIe https://jos.opwekking.nl/doneer.aspx. Deze gebruikt nog de 3.x versie.

Bij de 4.0.0. versie kan ik niet vinden hoe ik de lijst van iDeal issuers ophaal.

Ik kan wel dit gebruiken: 
```
using IPaymentMethodClient _paymentMethodClient = new PaymentMethodClient("{yourApiKey}");
PaymentMethodResponse paymentMethodResponse = await paymentMethodClient.GetPaymentMethodAsync(PaymentMethod.Ideal);
```

maar dan blijft de lijst van issuers null.

Bestaat de functionaliteit voor het ophalen van de bankenlijst nog of kan dat niet meer?

**Comment by Viincenttt** [comment]
Hi Henk,

I have not made any changes to the payment method client between version 3.6.0 and version 4.0.0. However, to resolve your issue I think you need to set the `includeIssuers` parameter to true when calling the `GetPaymentMethodAsync` method. For example:
```
using IPaymentMethodClient _paymentMethodClient = new PaymentMethodClient("{yourApiKey}");
PaymentMethodResponse paymentMethodResponse = await paymentMethodClient.GetPaymentMethodAsync(PaymentMethod.Ideal, includeIssuers: true);
```

Let me know if this helps :)

Kind regards,
Vincent

**Comment by henkkelder** [comment]
Dat was het inderdaad. Dank je :-)
