### ISSUE TITLE
Create 2.0 version

### ISSUE THREAD

**Issue by lgoudriaan** [Viincenttt/MollieApi#38]
Hey,

What about creating a 2.0 version with full api support (including molli connect) and removing the deprecated functions?

**Comment by Viincenttt** [comment]
Hi lgoudriaan,

Removing the deprecated functions will definitely be done in one of the next releases. Adding support for the other Mollie API's would certainly be a nice addition. Feel free to contribute. 

Kind regards,
Vincent

**Comment by lgoudriaan** [comment]
Do you want the pull requests on the master branch or a new branch?

**Comment by Viincenttt** [comment]
The master branch is fine :)
