### ISSUE TITLE
Missing fields in Mandate API?

### ISSUE THREAD

**Issue by drlee91** [Viincenttt/MollieApi#385]
Hello,

i want to create a Mandate for the method "directdebit".

`                    MandateRequest mandateRequest = new MandateRequest()
                    {
                        Method = "directdebit",
                        ConsumerName = mollieCustomerResponse.Name,
                        SignatureDate = DateTime.Now,
                        MandateReference = "REF-1234"
                    };`

https://docs.mollie.com/reference/create-mandate
In the Mollie documentation i have to transmit the fields "consumerAccount" and "consumerBic". For Paypal Mandates i have to add "consumerEmail" and "paypalBillingAgreementId".

The MandateRequest Class only got these fields:
  public record MandateRequest
  {
    public string Method { get; set; }
    public string ConsumerName { get; set; }
    public DateTime? SignatureDate { get; set; }
    public string? MandateReference { get; set; }
    public bool? Testmode { get; set; }
    public MandateRequest();
  }

How to create the Mandate or how to add these fields? 

Best Regards,
Lee

**Comment by martijnmelchers** [comment]
You'll have to use `new PayPalMandateRequest()` or `new SepaDirectDebitMandateRequest()` specific constructors

**Comment by drlee91** [comment]
> You'll have to use `new PayPalMandateRequest()` or `new SepaDirectDebitMandateRequest()` specific constructors

Thank you very much!
