### ISSUE TITLE
Add support for new Payment Link route

### ISSUE THREAD

**Issue by martijnmelchers** [Viincenttt/MollieApi#387]
Recently Mollie added the following route:

https://docs.mollie.com/reference/get-payment-link-payments

Support for this would be nice, if I have time I might add it myself and create a PR 🙌🏼

**Comment by Viincenttt** [comment]
Hi @martijnmelchers 

Support for this new endpoint has already been added in version 4.3.0.0 of the NuGet package: https://github.com/Viincenttt/MollieApi/releases/tag/4.3.0.0

Kind regards,
Vincent
