### ISSUE TITLE
Update PaymentUpdateRequest

### ISSUE THREAD

**Issue by melleg** [Viincenttt/MollieApi#389]
Great library!

I was wondering if support could be added for the following fields in PaymentUpdateRequest.cs:
- string? CancelUrl
- string? Method
- string? Locale
- boolean? TestMode

As per https://docs.mollie.com/reference/update-payment

**Comment by Viincenttt** [comment]
Thanks for the feedback @melleg , this has now been added in version 4.4.0.0 of the package.

**Comment by melleg** [comment]
Fantastic! Thank you!
