### ISSUE TITLE
Webhook with empty id

### ISSUE THREAD

**Issue by AbdellahF** [Viincenttt/MollieApi#39]
Hi,
does someone faced the same issue as me, when I make a payment the webhook input param is always empty?

**Comment by lgoudriaan** [comment]
Hi,

You will have to generate an URL to your own application where you handle a webhook and pass that in the payment request.

You can find more info here: https://www.mollie.com/en/docs/webhook

Hope this helps 😄

**Comment by calves07** [comment]
Facing a similar with problem...

```
[HttpPost]
[AllowAnonymous]
public async Task<ActionResult> Webhook(String id)
```

The function is called but id is empty. Any thoughts?

**Comment by whats-it-nl** [comment]
Try:
```C#
    [AllowAnonymous]
    [HttpPost("OnboardingWebhook")]
    [ProducesResponseType(StatusCodes.Status200OK)]
    public async Task<HttpStatusCode> Webhook([FromForm] string id)
```

**Comment by calves07** [comment]
Thanks, it works that way. Do you know why it failed with what I was using?
I thought it was because of the FromForm, I only tried with FromBody before but it didn't work as well.

**Comment by whats-it-nl** [comment]
A lot of trial and error and some debugging😉
