### ISSUE TITLE
Paymentmethod Blik not visible

### ISSUE THREAD

**Issue by Fit2Page** [Viincenttt/MollieApi#397]
Hi,

For one of our customers the paymentmethod Blik is not visible when sending in a normal - not specific - new PaymentRequest()

Is this a known issue?

Marc

**Comment by Viincenttt** [comment]
Hi Marc,

I can't offer any account specific assistance. For that, you'll have to contact the Mollie helpdesk. Let me know if you have any feedback regarding the library :)

Kind regards,
Vincent
