### ISSUE TITLE
Mollie Api V2

### ISSUE THREAD

**Issue by Erikmdr** [Viincenttt/MollieApi#398]
Do you support Mollie Api V2?

**Comment by Viincenttt** [comment]
Hi Erik,

Yes, this library supports Mollie API V2. Do you have any specific questions?

Kind regards,
Vincent

**Comment by Erikmdr** [comment]
Hi Vincent,

Bedankt voor de terugkoppeling. Ik krijg van Mollie de melding dat er
betalingen zijn gedaan met V1 en dat deze per 31-12-2024 niet meer
ondersteund wordt.



Op vr 27 sep 2024 om 19:21 schreef Vincent Kok ***@***.***>:

**Comment by Viincenttt** [comment]
Hi @Erikmdr ,

What version of the library are you using? Unless you are using a version that predates version 2.0.0 (released Aug 12, 2018), the library only uses V2 endpoints.

Kind regards,
Vincent

**Comment by Viincenttt** [comment]
Closing this for now, let me know if you have any further questions
