### ISSUE TITLE
415 Unsupported Media Type

### ISSUE THREAD

**Issue by NicoJuicy** [Viincenttt/MollieApi#40]
When i use the following code:

    var preparePayment = new Mollie.Api.Models.Payment.Request.PaymentRequest()
                    {
                        Amount = order.Totals.Total,
                        Locale = Helpers.ShopHelper.GetCurrentLanguage().ToLowerInvariant(),
                        Description = "Invoice °" + order.OrderNumber,
                        CustomerId = MollieId,
                        RedirectUrl = Url.Action("Finish", "Cart", new { }, Request.Url.Scheme),
                        WebhookUrl = Url.Action("MolliePaymentWebHook", "EndPoint", new { }, Request.Url.Scheme),
                        Metadata = order.Id.ToString()
                    };
    var response = await molliePay.CreatePaymentAsync(preparePayment);

The error that throws in the library = Unsupported Input received. But i added the source to check the underlying issue. Which gives 415 Unsupported Media Type.

I haven't changed anything in the code and it sets the UTF-8 and application/json content-type. But for some reason it just doesn't work.

Any thoughts? I have a feeling it could be a framework issue ( .net standard versions), but i'm not sure.

**Comment by lgoudriaan** [comment]
I've just tried to reproduce this. Is this issue already resolved?

**Comment by jeanpaulmars** [comment]
I get the exact same error message. I've checked using fiddler to see what happens and this is what happens:

I send the following:
POST https://api.mollie.nl/v1/payments HTTP/1.1
Accept: application/json
Authorization: Bearer test_Cz8AWxeg3ywp9EAxAAAy**********
Content-Type: application/json; charset=utf-8
Host: api.mollie.nl
Content-Length: 267
Expect: 100-continue

{"amount":0.9900,"description":"Verificatie","redirectUrl":"http://localhost:57216/Boeken/VerificatiePending?OrderNummer=RB2017.011762","method":"ideal","metadata":RB2017.011762,"webhookUrl":"https://www.MYSITE.COM/","locale":"nl_NL","customerId":"cst_hbwRmfhs36"}

and I get the following response from mollie:
HTTP/1.1 415 Unsupported Media Type
Server: nginx
Date: Tue, 28 Nov 2017 10:05:42 GMT
Content-Type: application/json; charset=utf-8
Content-Length: 126
Content-Security-Policy: frame-ancestors 'none'
X-Content-Type-Options: nosniff
X-Frame-Options: DENY
Access-Control-Allow-Credentials: true
Access-Control-Allow-Methods: GET, POST, HEAD, OPTIONS, DELETE
Access-Control-Max-Age: 300
Strict-Transport-Security: max-age=15552000; includeSubDomains

{"error":{"type":"request","message":"Unsupported input received","links":{"documentation":"https://www.mollie.com/en/docs"}}}

According to the documentation, error 415 usually happenes when you don't send your post in UTF-8. As you can see in the traffic, the charset is UTF-8, as it should be.

I've asked mollie for a response as well, but no response there yet.

**Comment by lgoudriaan** [comment]
Hi @jeanpaulmars,

Can you try the same request without metadata?
The value of the metadata isn't valid json, so maybe that's the problem.

**Comment by jeanpaulmars** [comment]
When I leave the metadata empty/null it works correctly. Is is possible to have CreatePaymentAsync throw an exception if it encounters problems a problem with the input (such as invalid json) instead of passing it on towards the api of mollie? 
(An exception stating "Unable to parse metadata field" is much more helpful while debugging then the response from mollie "unsupported input received".)

**Comment by lgoudriaan** [comment]
Guess we have found a bug ;)
I will try to fix this tonight in a PR.

**Comment by lgoudriaan** [comment]
@jeanpaulmars, @NicoJuicy I found out after looking deeper into this that you can set metadata only directly with an JSON string.

If you just want to pass an extra id use the SetMetaData method. And Getmetadata<T>() to retreive.

@Viincenttt maybe set the metadata property to private?

**Comment by jeanpaulmars** [comment]
Or a string getter/setter which stores it internally in a json? I really prefer to be able to make a single call without being forced to call a separate SetMetaData() function. (So I can use it the same way as @NicoJuicy describes in his first message.

**Comment by Viincenttt** [comment]
I'm not sure if I understand the problem. The Metadata property on a PaymentRequest is a string, so you can pass a JSON string to the mollie API. To make it easier to serialize your own classes to a JSON format, I have added the Get/Set metadata functions. 

Use the Metadata property if you want to set the JSON string manually. Use the Set/GetMetadata method if you want built-in serialization of complex objects. 

This library doesn't validate any data you send to the Mollie API. It is up to the Mollie API to validate your data and send back any errors. If the error Mollie gives you isn't clear enough, please contact Mollie and provide them with your feedback.
