### ISSUE TITLE
Passing Testmode to CaptureClient.CreateCapture result in Unprocessable Entity

### ISSUE THREAD

**Issue by RickvF** [Viincenttt/MollieApi#400]
When passing the testmode = true in CreateCapture(string paymentId, CaptureRequest captureRequest, bool testmode = false), this call results in an 'Unprocessable Entity - Non-existent query parameter "testmode" for this API call.' exception.

**Comment by Viincenttt** [comment]
Hi @RickvF ,

Thanks for reporting this. The testmode parameter should be in the request body, not in the query string as it's currently implemented. I've created a PR to fix this.

**Comment by RickvF** [comment]
Thanks again for picking this up quickly

**Comment by Viincenttt** [comment]
This is now fixed in 4.4.2.0
