### ISSUE TITLE
System.IO.FileNotFoundException System.Runtime, Version=4.0.10.0

### ISSUE THREAD

**Issue by wvduffelen** [Viincenttt/MollieApi#47]
With the 1.4.4.1 version of the Mollie API there's a dependency missing. I didn't have the NETStandard.Library installed and got an error. After installing the NETStandard.Library the latest version also works. Another solution would be to downgrade to 1.4.4. 

Line 22 at: https://github.com/Viincenttt/MollieApi/blob/0ca76f0dff7b9f436e931ecb976c2960f3e7a8c8/Mollie.Api/Mollie.Api.csproj

**Comment by Viincenttt** [comment]
Thanks for letting me know. I'll fix this when I release the new version.

**Comment by Viincenttt** [comment]
The new version has been released (1.5.0)
