### ISSUE TITLE
PaymentResponse does not contain Details field with IdealPaymentResponseDetails

### ISSUE THREAD

**Issue by jeanpaulmars** [Viincenttt/MollieApi#49]
I wish to get the IBAN of a customer that has done a payment. 

If I do
```
PaymentClient paymentClient = new PaymentClient(MollieApiKey);
var payment = paymentClient.GetPaymentAsync(item.BetalingId).Result;
var myDetails=payment.Details;
```
the `Details` does not exist. In debug is it is available, so (for now) I've rewritten the code to
```
PaymentClient paymentClient = new PaymentClient(MollieApiKey);
dynamic payment = paymentClient.GetPaymentAsync(item.BetalingId).Result;
if (payment != null && payment.Details != null)
{
    var bankAccount = payment.Details as Mollie.Api.Models.Payment.Response.IdealPaymentResponseDetails;
    if (bankAccount != null)
    {
        item.Iban = bankAccount.ConsumerAccount;
        item.DateChecked = currentDate;
    }
}
```
And then it works correctly. However, I'd love to see that the `IdealPaymentResponseDetails` field is added to the `PaymentResponse` object.

**Comment by Viincenttt** [comment]
Hi jeanpaulmars,

The GetPaymentAsync method returns a PaymentResponse object. This object can be an IdealPayment, Creditcard payment or some other type of payment object. Therefor it is not possible to add the IdealPaymentResponseDetails to the PaymentResponse class. 

It is possible to cast the PaymentResponse object to a IdealPaymentResponse object, which will allow you to access the IdealPaymentResponseDetails field. Try the following code:
```csharp
PaymentClient paymentClient = new PaymentClient(this.ApiTestKey);
IdealPaymentResponse result = paymentClient.GetPaymentAsync(id).Result as IdealPaymentResponse;

IdealPaymentResponseDetails details = result.Details;
```
