### ISSUE TITLE
New package for subscriptions

### ISSUE THREAD

**Issue by owingruters** [Viincenttt/MollieApi#5]
Hi Vincent,

I see that you also implemented the subscription API. Great!! 
Are you planning to package that fantastic new feature as well in a v1.3.3?
(p.s. sorry to make an 'issue' for it, but I have no idea how to ask you in another way...)

Regards,
Owin

**Comment by Viincenttt** [comment]
Hi Owin,

I haven't finished testing the subscription API yet, but I expect to finish it somewhere in the coming days. I'll keep you updated. 

Regards,
Vincent

**Comment by owingruters** [comment]
Great! 



Op 18 jul. 2016 10:12, bij 10:12, Vincent Kok <notifications@github.com> schreef:

**Comment by Viincenttt** [comment]
Hi Owin,

I have created a new version 1.3.3 which includes support for the subscription API. 

Regards,
Vincent

**Comment by owingruters** [comment]
Super!

Such a good timing,because I actually was going to work on it today! :)

Owin

**Comment by owingruters** [comment]
Hi Vincent,

Just wanted to inform you that I have been accidently using your test API
Key :|
So you might have some payments, customers, mandates and subscriptions on
you account.

Sorry about that!

BTW, have you found a way to test the webhook of the recurring payments.
I'd rather not wait 1 week to be able to test my code :)

Regards,
Owin

**Comment by Leonm91** [comment]
Hi Ortwin,

In order for the recurring payment to work you'll need to get a mandate. You can setup a €0,01 payment through iDeal. I did this as follows:

`
var result = await this._mollieClient.CreatePaymentAsync(new RecurringSubscriptionRequest
            {
                Amount = 0.01M,
                CustomerId = user.MollieInfo.MollieCustomerId,
                Description = "Mandaat voor automatische incasso School of Music",
                RecurringType = Mollie.Api.Models.Payment.RecurringType.First,
                RedirectUrl = @"https://xxx.xxx",
                Method = Mollie.Api.Models.Payment.PaymentMethod.Ideal,
                Locale = Mollie.Api.Models.Payment.Locale.NL
            });


            return Redirect(result.Links.PaymentUrl);
`

You can send a payment request to Mollie once you have at least 1 valid mandate.
This **will** work. I tested it with 3 payments and in about 1 or 2 weeks you'll see the result on your Mollie balance.

**Comment by owingruters** [comment]
Hi Leon,

I have no issue creating the mandate nor the subscription. That all works
But I can only test First payment do not want to wait 1 week to see if my
code for recurring type is also working.

Thanx,

Owin

**Comment by Viincenttt** [comment]
Hi,

I don't actually use recurring payments in my own applications, so I can't be of much help. Maybe you could set the interval period of the recurring payment to 1 day? At least it would be faster then waiting an entire week. 

PS: Don't worry about the API key. Sometimes I forget to remove it before pushing my code to GitHub, so it's my own fault. I'll request a new key. 

Regards,
Vincent
