### ISSUE TITLE
System.AggregateExceptions

### ISSUE THREAD

**Issue by pujarasanni027** [Viincenttt/MollieApi#56]
Hi.,

I'm new at this., and going to implement into my system. Need help about mollie refund.
Thanks.

```
this._refundClient = new RefundClient(apiKey);
RefundRequest requestModel = new RefundRequest()
{
                Amount = 25,
                Message = 'Refund_Remarks'
};

var response = this._refundClient.CreateRefundAsync(PaymentId, requestModel).Result; // this line crashed
return response; 
```

**var response = this._refundClient.CreateRefundAsync(PaymentId, requestModel).Result; // this line** 
from this line , i'm getting Error like:

   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
Inner Exception - {"Unknown field: message"}

**Comment by lgoudriaan** [comment]
Hi @pujarasanni027,

The message parameter seems to be renamed to description.
For now you can try to set the message to null.

I will to try to do a PR to sync up the refundclient

**Comment by pujarasanni027** [comment]
Hi lgoudriaan,
Thanks for your Help.

Yes i got it. and changed code as per your comment and it's working fine as per expectation.

Thanks again.
