### ISSUE TITLE
Some documentation mistakes

### ISSUE THREAD

**Issue by DianaKoenraadt** [Viincenttt/MollieApi#57]
The following lines of comments are incorrect:

https://github.com/Viincenttt/MollieApi/blob/master/Mollie.Api/Models/Payment/Request/PaymentRequest.cs#L26

https://github.com/Viincenttt/MollieApi/blob/master/Mollie.Api/Models/Payment/Request/PaymentRequest.cs#L42

Thanks for your work in developing this!

**Comment by Viincenttt** [comment]
Merged these changes into master
