### ISSUE TITLE
Payment screen is by default in german

### ISSUE THREAD

**Issue by wielvanraaij** [Viincenttt/MollieApi#6]
Hi Vicent,

I've implemented your molly API which was really easy to implement. 

The only problem i'm experiencing is that the default value of the property Locale in PaymentRequest is Local.DE. This is probably because that is the fist value of the enumeration.

**Comment by Viincenttt** [comment]
Hi Wielvanraaij,

I'm glad to hear the API is easy to use. 

I have been able to reproduce the issue you are having and I have committed a fix to the repository. The Locale property on the PaymentRequest is now nullable. I'm planning to release a new version/nuget package that includes this fix today or tommorow. 

Kind regards,
Vincent

**Comment by Viincenttt** [comment]
I released a new version that includes a bugfix for the Locale problem. Please view the full list of changes  [here](https://github.com/Viincenttt/MollieApi/releases/tag/1.3.4)
