### ISSUE TITLE
Probleem met API key

### ISSUE THREAD

**Issue by jbosch111** [Viincenttt/MollieApi#61]
While creating a payment (like in the example) I always get the error: The provided token isn't an oauth token.

Retreiving a list of payment methods works fine.

What could be the issue ?

**Comment by lgoudriaan** [comment]
Hi,

You probably have filled the testmode field which is only for Oauth tokens like you can see here: https://github.com/Viincenttt/MollieApi/blob/dcd69373f7b054b0490890ec2e039d2841dd5011/Mollie.Api/Client/PaymentClient.cs#L16-L17

You can just leave this property empty.

**Comment by Viincenttt** [comment]
Hi jbosch, 

Did you manage to resolve this issue?

Kind regards,
Vincent

**Comment by jbosch111** [comment]
Hi Vincent,

Yes that soved my problem )
Sorry for the late reply, I was kinda busy...

Jim

**Comment by yadavrg** [comment]
> Hi,
> 
> You probably have filled the testmode field which is only for Oauth tokens like you can see here:
> 
> https://github.com/Viincenttt/MollieApi/blob/dcd69373f7b054b0490890ec2e039d2841dd5011/Mollie.Api/Client/PaymentClient.cs#L16-L17
> 
> You can just leave this property empty.

This resolves the issue, but it shouldn't work in this way. We should be able to request with **testmode** paramter as specified in original Mollie document, otherwise it will always return results in Live mode.

`testmode`  boolean   OPTIONAL

- Set this to true to get a payment made in test mode. If you omit this parameter, you can only retrieve live mode payments.

**Comment by Viincenttt** [comment]
Hi @yadavrg ,

It depends. If you are using a test api key, you do not need to use the testmode parameter at all. All requests you do, will be in test mode. If you are using a oath access token, you do need to use the Testmode property to specify you are using test mode. 

I hope this clears things up.

Kind regards,
Vincent

**Comment by yadavrg** [comment]
@Viincenttt got it now, thanks for clarification so quickly.
