### ISSUE TITLE
The requested value inghomepay cannot be found

### ISSUE THREAD

**Issue by MarcoDieleman** [Viincenttt/MollieApi#64]
When I call GetPaymentListAsync I get the error above. This used to work fine, but is failing since a few days. Has there been a change at the Mollie API? Is there a way to fix this?

**Comment by Viincenttt** [comment]
Hi Marco,

I am not able to reproduce this issue. Can you provide me with a code snippet that demonstrates the problem? I am able to create/retrieve inghomepay payments with issues. Perhaps you are using an old version of the API client? Please try updating the Nuget package.

Kind regards,
Vincent

**Comment by MarcoDieleman** [comment]
Hi Vincent,
I've update the package to 1.5.2. In the WebApplicationExample I can retrieve a list of payments (with a Live key). So upgrading has fixed that issue, but in my project I get the error "The requested value eps was not found".

In my code I call this class:

public static ListResponse<PaymentResponse> GetPaymentList(int offset, int count)
{
    ListResponse<PaymentResponse> response = new ListResponse<PaymentResponse>();
    response = paymentClient.GetPaymentListAsync(offset, count).Result;
    return response;
}

This used to work fine.

**Comment by Viincenttt** [comment]
Hi Marco,

Thank you for your reply. The EPS payment method was added in june and I did not add it to the list of available payment methods yet. I just released a new version of the nuget package 2.0.0.1, where the EPS and Giropay methods are supported. 

Let me know if you need any further help or if I can close this issue. 

Kind regards,
Vincent

**Comment by MarcoDieleman** [comment]
Hi Vincent,
I've updated my code with the new payment methods and everything is running as expected. You can class the call now. Thank you for your help.

**Comment by Viincenttt** [comment]
Hi Marco,

Good to know! Let me know if you run into any other issues.

Kind regards,
Vincent
