### ISSUE TITLE
MisterCash

### ISSUE THREAD

**Issue by pujarasanni027** [Viincenttt/MollieApi#66]
Hi All,

Can any one tell me, Which Payment request model is required for **MisterCash** ?

Thanks All

**Comment by Viincenttt** [comment]
Hi pujarasanni027,

For MisterCash you can simply create a PaymentRequest object and set the "Method" property to PaymentMethod.MisterCash.

Kind regards,
Vincent

**Comment by pujarasanni027** [comment]
Hi @Viincenttt 

Thanks for your reply.

Working !!!

Thanks.
