### ISSUE TITLE
Update Subscriptions

### ISSUE THREAD

**Issue by dsbaiz** [Viincenttt/MollieApi#67]
Hey,

Mollie has the option to update an existing subscription in their API's:
https://docs.mollie.com/reference/v2/subscriptions-api/update-subscription

I don't currently see this as possible using this API? Is it possible to add the update function to the API?

Thank you!

**Comment by Viincenttt** [comment]
Hi dsbaiz,

The documentation you've linked to is the version 2 API, but the current client implementation only supports version 1. I am working on adding version 2 support, but it's not done yet. Version 1 of the API does not support updating subscriptions. 

Kind regards,
Vincent

**Comment by Viincenttt** [comment]
Hi dsbaiz,

The documentation you've linked to is to the Mollie API version 2. Version 1.5.2 of my API client only offered support for Mollie API version 1. I have added Mollie API v2 support today in Mollie API version 2.0.0, but unfortunatly it is not backwards compatible with 1.5.2. 

I will add support for the update subscription method soon. If you want, you can also add the method yourself and create a pull request. It shouldn't be hard :)

Kind regards,
Vincent

**Comment by Viincenttt** [comment]
I have added support for the update subscription method. This will be added to the next version of the mollie api library.

**Comment by Viincenttt** [comment]
Reopened untill version is released

**Comment by Viincenttt** [comment]
The 2.0.2.0 version has been released, so this issue should now be resolved.
