### ISSUE TITLE
Support for the Mollie Reseller API

### ISSUE THREAD

**Issue by wouterroos** [Viincenttt/MollieApi#69]
Hi,

Do you plan on supporting the [Reseller API](https://help.mollie.com/hc/en-us/articles/214016745-Where-can-I-find-the-API-documentation-for-resellers-) any time soon? We're currently doing a project on which we plan to use your abstraction in order to interface with the Mollie API, but we also need access to the Reseller API.

Thanks in advance!

Regards,
Wouter Roos

**Comment by Viincenttt** [comment]
Hi Wouterroos,

Unfortunatly I am not a reseller, so I do not have access to the reseller API. This means I would have no way to test the reseller API myself. 

Kind regards,
Vincent

**Comment by Viincenttt** [comment]
I would like to add that if you or someone else can implement the reseller API and create a pull request, I will merge it into the main branch.

**Comment by wouterroos** [comment]
Great! We have it planned for next week. The plan is to use the same programming model as StrongGrid, so I will create a pull request when we're done.

**Comment by Viincenttt** [comment]
Great, I am looking forward to your pull request :)

**Comment by Viincenttt** [comment]
Hi wouterroos,

Is there any update regarding the Reseller API? Are you running into any issues with the Mollie Api code? 

Kind regards,
Vincent

**Comment by wouterroos** [comment]
Hi @Viincenttt,

We're currently running an implementation of the `ResellerClient`, inspired by the programming model/project structure you used in the `MollieApi` package. This should make a pull request towards this repository trivial. However, at the moment we've only implemented the API operations we need for our project, so there is some work to be done there before we can create a proper pull request into your repository. We did however create a generic `BaseClient` which makes implementing those operations as easy as defining them on the `IResellerClient` interface, creating the accompanying Model classes with the proper `[XmlElementAttributes]` for mapping and invoking a generic POST method on the `BaseClient`. 
When attempting to integration test our current implementation, we've noticed that this is quite difficult to do, mostly due to the way Mollie built the API. The 'test mode' capability for this API are limited to the `account-create` action, so any other tests would have to be executed against a 'live' environment, which is difficult to obtain since Mollie 'verifies' each account to make sure it's linked to a valid an existing company. All this makes it difficult to guarantee quality on the code we've written so far. 
We've contacted Mollie on what their plans are as to improve testing capabilities, but their response was: 'Good idea, we'll forward it to our devs', so I'm not expecting anything from their side any time soon.

Do you have any ideas on how we can approach these issues?

**Comment by Viincenttt** [comment]
Hi wouterroos,

Thank you for your reply. I have encountered the exact same issues as you regarding the testing capabilities of the Mollie API. Not all of the Mollie API's/API methods can be tested using a test api key. This also makes it impossible to write integration tests for some of the API methods. Unfortunatly I haven't found a solution for this. 

Please let me know if you need any help regarding the implementation of the Reseller API. 

Kind regards,
Vincent

**Comment by wouterroos** [comment]
@kurtwilbies Hi,

Unfortunately, I did not yet find the time to create a pull request yet. What I propose we do is that I commit our code 'as is' (that is, with only the operations we currently use implemented) and maybe we could split the workload of implementing the other operations?

**Comment by kurtwilbies** [comment]
Hi @wouterroos ,

IWell, you could share your code, a link or dropbox. And could you provide some docs. Then I can implement those operations.

**Comment by wouterroos** [comment]
Hi,

I'm currently investigating the possibility to create a pull request. One of the 'issues' I'm having is that some of the code we use is not compatible with `netstandard1.2`. @Viincenttt would it be an issue to upgrade the netstandard version to something more recent? Initial testing indicates that `netstandard1.3` should work (with some additional NuGet packages), but perhaps migrating to `netstandard2.0` is also an option?

**Comment by wouterroos** [comment]
Hi, 

Please see #87 for a preliminary pull request of our changes. This is a 1:1 copy of our current (local) implementation so there might be some stuff that needs to be changed. Please note that this PR also incorporates a solution for #86 . Feedback is welcome, if any changes need to be done please let me know.

**Comment by kurtwilbies** [comment]
@wouterroos,

Thanks, I'll review your request asp

**Comment by Viincenttt** [comment]
The Reseller API has been deprecated:
> The Reseller API has been deprecated. Only selected partners still have access to this legacy functionality. As an alternative, we recommend using Mollie Connect and the Mollie v2 API.
Source: https://docs.mollie.com/reference/reseller-api/guides/overview
