### ISSUE TITLE
Adding CustomerId and RecurringType to PaymentResponse Model

### ISSUE THREAD

**Issue by owingruters** [Viincenttt/MollieApi#7]
Hi vincent,

I had some contact with Mollie last week on recurring payments, and I found out that the customerId and recurringType are also properties of the payment response. 
`{"resource":"payment","id":"tr_xxXXxxXX","mode":"test","createdDatetime":"2016-07-28T14:06:49.0Z","status":"open","expiryPeriod":"PT13M39S","amount":"0.01","description":"Test","method":null,"metadata":null,"details":null,"profileId":"pfl_xxXXxxXX","customerId":"cst_xxXXxxXXxx","recurringType":"first","links":{"paymentUrl":"https://www.mollie.com/payscreen/select-method/XXxxXXxx","redirectUrl":"http://mollie.com"}}`

Since I did not see them in your Paymentsresponse model I thought I would add them, test them and offer you a pull request.

However, when trying to test using the SimpleExample or WebappplicationExample I recieved unhandled exceptions in both, also in the original version without my changes:
Exception: An error has occured while performing an action on the Mollie Api. Please view the Error property for more information about the exception.
Error property: {Mollie.Api.Models.MollieErrorMessage}
So that does not help me much...

Is this something that you can reproduce?
After this error is solved, would you like me to add these 2 properties to the PaymentResponse via a pull request?

Regards,
Owin

**Comment by owingruters** [comment]
I can see in the debugger:  Unauthorized request.
I tried with my own API key and then it does work!

Just be aware that your API key is not working anymore.

My second question is still valid. Do you want me to do the changes?

**Comment by Viincenttt** [comment]
Hi Owin, 

Don't worry about the API key. I requested a new key a few weeks ago because I accidently committed it to the repository. 

I have added the properties to the PaymentResponse class and will release a new version as soon as possible. 

Kind regards,
Vincent

**Comment by owingruters** [comment]
So cool!

BTW, I have asked Mollie how to test recurring payments and the answer is it cannot be tested. They do not actually call the webhook after the defined time interval, but only the ‘First’ payment

**Comment by Viincenttt** [comment]
Hi Owin,

I have released a new version that adds the CustomerId and RecurringType properties. This release also adds alot of other missing fields, some bugfixes and other features. Please view the full change list [here](https://github.com/Viincenttt/MollieApi/releases/tag/1.3.4). 

Regards,
Vincent
