### ISSUE TITLE
Mollie.Api.Models.Amount cannot be serialized

### ISSUE THREAD

**Issue by pGuernseyPlayer** [Viincenttt/MollieApi#72]
System.InvalidOperationException: There was an error reflecting type 'Mollie.Api.Models.Payment.Response.Specific.SepaDirectDebitResponse'. ---> 
System.InvalidOperationException: Cannot serialize member 'Mollie.Api.Models.Payment.Response.PaymentResponse.Amount' of type 'Mollie.Api.Models.Amount', see inner exception for more details. ---> 
System.InvalidOperationException: Mollie.Api.Models.Amount cannot be serialized because it does not have a parameterless constructor. 

code:

                    specificResult = (Mollie.Api.Models.Payment.Response.Specific.SepaDirectDebitResponse)result;

                    XmlSerializer xmlizer = new XmlSerializer(specificResult.GetType());
                    using (var sw = new StringWriter())
                    {
                        using (XmlWriter writer = XmlWriter.Create(sw))
                        {
                            xmlizer.Serialize(xmlWriter: writer, o: specificResult);

                            response_raw = sw.ToString(); 
                        }
                    }

**Comment by Viincenttt** [comment]
Hi pGuernseyPlayer,

In the future it would be helpfull if you could include a question when opening an issue instead of just copy/pasting the exception message and some code. 

If I understand correctly you are trying to serialize a payment response, but are unable to because the Amount class does not have a parameterless constructor. Am I right? 

Kind regards,
Vincent

**Comment by pGuernseyPlayer** [comment]
Hi Vincent,
Yes, I am serializing the payment response as xml and am encountering the InvalidOperationException. I downloaded the code, and added parameterless constructors to these classes:

Amount
SepaDirectDebitResponseDetails
PaymentResponse

I then successfully retested my code.
Sorry for not properly formatting my question.

-- pgp [Paul Guersney Player]

**Comment by Viincenttt** [comment]
Hi pGuernseyPlayer,

I have just released version 2.0.1.1 of the API that adds a parameterless constructor to the Amount class. The SepaDirectDebitResponseDetails and PaymentResponse classes do not have any constructors defined, so they have a parameterless constructor by default. 

The issue should be resolved when you download the latest NuGet package. 

Kind regards,
Vincent
