### ISSUE TITLE
Insufficient balance Exception while refund

### ISSUE THREAD

**Issue by pujarasanni027** [Viincenttt/MollieApi#73]
Hi Team,

I found problem with refund to working with.

this code returns exception while insufficient balance in our account while it's on 
LIVE Transaction.

```
 RefundResponse MollieResponse = null;
          MollieResponse =   _mollieApi.Refund(PaymentId, LIVE_APIKey, 2500);
            return MollieResponse;
```

Please Help whats the wrong with this code and how to test with TEST Mode.

Thanks in advance.

**Comment by Viincenttt** [comment]
Hi pujarasanni027,

What is the exception you are getting? Are you getting a MollieApiException or is it some other type of Exception?

Kind regards,
Vincent

**Comment by pujarasanni027** [comment]
Hi @Viincenttt 

Refund has been done using LIVE_API KEY -> Live Account

and I'm testing using TEST_API KEY and in TEST Account such a scenario seems not like possible,
because we refund against payment even if we do not have balance.

So i can i produce such a scenario in TEST Mode

Need you Help / Suggestion

Thanks
- Sanni Pujara

**Comment by Viincenttt** [comment]
Hi pujarasanni027,

I am afraid it's not possible to test this scenario using a test api key. I understand the exception is thown by the Mollie API, but I was wondering if it's throwing an exception of type MollieApiException. 

If it is, you should catch the exception in your code and handle it accordingly. 

Kind regards,
Vincent

**Comment by Viincenttt** [comment]
Closed for now, if you have any further questions please let me know.
