### ISSUE TITLE
CreditCardSecurity value '3dsecure' gives conversion error.

### ISSUE THREAD

**Issue by erwinvk** [Viincenttt/MollieApi#75]
Thanks for the library, really useful.

fix for issue:
put
[JsonConverter(typeof(StringEnumConverter))]

above
public CreditCardSecurity? CardSecurity { get; set; }

in CreditCardPaymentResponse

/edit
also applies to:
public CreditCardFeeRegion? FeeRegion { get; set; }
public CreditCardFailureReason? FailureReason { get; set; }

**Comment by Viincenttt** [comment]
Thanks, I just added your suggested fix in 6df727f
