### ISSUE TITLE
HttpWebRequest: The request was aborted: Could not create SSL/TLS secure channel

### ISSUE THREAD

**Issue by jonathanjto** [Viincenttt/MollieApi#76]
Hello,

I had a very weird issue when calling "CreatePaymentAsync" method on "PaymentClient".
I got an error "HttpWebRequest: The request was aborted: Could not create SSL/TLS secure channel"

The weird stuff it's that happened only once ... I never had the issue in test and I already have some live payments (before and after the error).

Have you an idea of what happened here? 

Here is the stack trace

![sans titre](https://user-images.githubusercontent.com/816054/46332619-8014d400-c61d-11e8-9a08-da61f185a5ba.png)

**Comment by Viincenttt** [comment]
Hi jonathanjto, 

Very strange, I have not experienced this issue before. If it only happened once then it could have been an issue with the Mollie API being unavailable during this request. 

My suggestion would be to monitor the logs to see if the error happens again. I will close this issue, but do let me know if the error happens again. 

Kind regards,
Vincent

**Comment by jonathanjto** [comment]
Hi,

The problem occurs once again but calling another method

PaymentResponse payment = await mollieClient.GetPaymentAsync(paymentId)

I've got an error in windows system event logs 

Erreur	05/10/2018 10:30:08	Schannel	36887	Aucun

Une alerte irrécupérable a été reçue du point de terminaison distant. Le code d’alerte irrécupérable défini par protocole de TLS est 20.
