### ISSUE TITLE
no method returns paymentmethod.ideal

### ISSUE THREAD

**Issue by rayray4105** [Viincenttt/MollieApi#84]
Hi,

I have been playing around with creating payments using the mollie api and it works great so for. I have run into an issue (I think). When I do not add .method the payment response does contain a method. I would like generate a payment link only without a method. In my case it returns ideal as the selected method and as a result the payment expires after 15 minutes. 

According to Mollie this is a difference between a session and a link. A link is always active until payment is completed (after using a link a payment session is started).

Ideal is the only payment I have activated on the dasboard. Am I doing something wrong?

**Comment by Viincenttt** [comment]
Hi rayray4105,

I'm not sure I understand the problem. I am not able to reproduce the issue. Please see the following code:
```c#
PaymentRequest paymentRequest = new PaymentRequest() {
    Amount = new Amount(Currency.EUR, "100.00"),
    Description = "Description",
    RedirectUrl = this.DefaultRedirectUrl
};

PaymentResponse result = await this._paymentClient.CreatePaymentAsync(paymentRequest);
```

When I take a look at the result, the Method property is set to null. 

Kind regards,
Vincent

**Comment by rayray4105** [comment]
Hi Vincent,

As it turns out the method will be returned if only one paymentmethod has been actived on the Mollie dashboard. Adding as second method returned null after running the code again.

`        Dim PaymentClient As IPaymentClient = New PaymentClient(apiKey)
        Dim paymentRequest As PaymentRequest = New PaymentRequest() With {
            .Amount = New Amount(Currency.EUR, "1.00"),
            .Description = "Test payment of the example project",
            .RedirectUrl = "http://www.google.nl"
        }`
My problem however is that the payments expire after 15 minutes. I would like to create a payment link and not a session. I am wondering if this is even possible.

**Comment by Viincenttt** [comment]
Closed due to inactiveness
