### ISSUE TITLE
String for Value

### ISSUE THREAD

**Issue by peterdebruijn** [Viincenttt/MollieApi#85]
I upgraded to the 2.0 version and inspected the code. However, I was confused about the new 'Amount' class. The property 'value' is a 'string'. Why? I would have expected a decimal. You'll have all kinds of cultural issues now...

**Comment by Viincenttt** [comment]
Hi peterdebruijn,

This was not my decision, but Mollie's decision when they implemented the API. The Mollie API expects a string for the currency value. Take a look at the documentation of the create payment API method: https://docs.mollie.com/reference/v2/payments-api/create-payment 

Kind regards,
Vincent
