### ISSUE TITLE
Is List Customer Payments supported?

### ISSUE THREAD

**Issue by wouterroos** [Viincenttt/MollieApi#86]
Hi @Viincenttt,

We're currently looking into the List Customer Payments operation (https://docs.mollie.com/reference/v2/customers-api/list-customer-payments) of the Mollie v2. Unfortunately the MollieApi package doesn't seem to have a client that supports this call, is this correct? 

Thanks in advance,

Regards,
Wouter

**Comment by wouterroos** [comment]
solved this in #87 by returing Payments link on CustomerResponse

**Comment by Viincenttt** [comment]
Hi Wouter, 

Thanks for letting me know. I have added support for this endpoint in the 2.0.2.0. Will update once this version is released. 

Kind regards,
Vincent

**Comment by wouterroos** [comment]
@Viincenttt  Great, thanks!

**Comment by Viincenttt** [comment]
The 2.0.2.0 version has been released, so this issue should now be resolved.

**Comment by wouterroos** [comment]
Great, thanks!
