### ISSUE TITLE
Metadata must be JSON?

### ISSUE THREAD

**Issue by Alex-van-der-Peet** [Viincenttt/MollieApi#88]
Putting a regular string in the request.Metadata field causes the CreatePaymentAsync function to fail, perhaps because the Metadata field is marked with [JsonConverter(typeof(RawJsonConverter))] ?

The Mollie documentation does not state this must be JSON, it should also allow regular strings. Putting a JSON formatted string in the Metadata field yields success.

**Comment by Viincenttt** [comment]
The 2.0.2.0 version has been released, so this issue should now be resolved.
