### ISSUE TITLE
Mollie gets HTTPresponse 502 back from webhook

### ISSUE THREAD

**Issue by owingruters** [Viincenttt/MollieApi#9]
Hi Vincent,

I have implemented the webhook like this

```
        [HttpPost]
        public async Task<System.Net.Http.HttpResponseMessage> WebHook([System.Web.Http.FromBody] string id)
{
            string paymentId = id;

            //Do things (that do not throw an error)

            return new HttpResponseMessage(HttpStatusCode.OK);
}
```

I tried a few methods of returning a httpresponse 200, but it keeps failing which keeps Mollie retrying the webhook call.
I cannot see an implementation in your test project of the webhook and that makes sense, but you must have one, so my question is how do you let Mollie know that their webhook call succeeded?

Thanx a bunch!

Owin

**Comment by Viincenttt** [comment]
Hi Owin,

Here's an example I copied from one of my real life projects: 
```c#
[HttpPost]
public async Task<ActionResult> ProcessPayment(string id) {
    await this._paymentService.ProcessPayment(id);
    return new HttpStatusCodeResult(HttpStatusCode.OK);
}
```

Your code looks fine to me. Is this a production or a test environment? Make sure your site publicly available on the internet and isn't blocked by a firewall or something. 

You could also try to post a payment id to site yourself to see if that also gives the same 502 error.

**Comment by owingruters** [comment]
Thanx!

It's a test environment.  It is publicly available in the cloud,  so there
should not be a firewall.
It is also getting reached,  because my code is firing and handled, only
the response is not correct.

I see a difference between our codes is that you use an actionresult where
I have used an HttpResponseMessage. I changed it and now I only get 1 call,
so I think they now recieve correct responsecode. Thanx!

Owin

**Comment by Viincenttt** [comment]
Good to hear it's working.

**Comment by DianaKoenraadt** [comment]
Sorry to open such an old topic, but could someone help please?

I've tried everything from [FromBody] to just plain string and whatever I do, Mollie gets a 404. 

```
// Nope
[HttpPost]
public HttpResponseMessage Post(string id)
{
    return new HttpResponseMessage(HttpStatusCode.OK);
}

// Nope
[HttpPost]
public HttpResponseMessage Post([FromBody] string id)
{
    return new HttpResponseMessage(HttpStatusCode.OK);
}
```

When I *completely remove* the id parameter from my method, then Mollie can call it. But obviously, then I don't have the paymentId! :(

```
// Works, but no id
[HttpPost]
public HttpResponseMessage Post(string id)
{
    return new HttpResponseMessage(HttpStatusCode.OK);
}
```

My routing is just default, shouldn't be a big deal right?

```
config.Routes.MapHttpRoute(
                name: "DefaultApi",
                routeTemplate: "api/{controller}/{id}",
                defaults: new { id = RouteParameter.Optional }
            );
```

Can anyone shed some light on this? I'm pulling my hair out....

**Comment by Viincenttt** [comment]
Looks like it might be a routing issue. Are you able to post to the API controller method yourself? You can test using using a simple plugin such as Postman (https://www.getpostman.com/)

**Comment by DianaKoenraadt** [comment]
Hi Vincent,

thank you kindly for your reply.

I've been using Postman, but I am struggling to figure out what to enter for the body:

- form-data entering "id" and "test" fails magnificently with an UnsupportedMediaTypeException
- raw fares no better: If I enter "test", my action is called :) but the string 'id' is still null :(

Do you know what the exact format is?

I wish they'd just chosen a querystring parameter.... Would be so much easier.
