### ISSUE TITLE
Why is ExpiredAt a string?

### ISSUE THREAD

**Issue by DianaKoenraadt** [Viincenttt/MollieApi#90]
Hi, I'm upgrading from v1 to v2. In the PaymentResponse, there's

        public DateTime? FailedAt { get; set; }
        public string ExpiredAt { get; set; }
        public DateTime? ExpiresAt { get; set; }
        public DateTime? CanceledAt { get; set; }
        public DateTime? PaidAt { get; set; }

Is there a specific reason why ExpiredAt is a string?

**Comment by Viincenttt** [comment]
Hi,

I honestly have no idea why I made that a string. Probably just a silly typing mistake. 

Kind regards,
Vincent

**Comment by Viincenttt** [comment]
I have resolved this issue in the 2.0.2.0 branch. I will update this ticket once this version has been released.

**Comment by DianaKoenraadt** [comment]
Great, thanks! :)

**Comment by Viincenttt** [comment]
The 2.0.2.0 version has been released, so this issue should now be resolved.
