### ISSUE TITLE
I cannot find enum for the Klarna payment method

### ISSUE THREAD

**Issue by Fit2Page** [Viincenttt/MollieApi#91]
I cannot find enum for the Klarna payment method

**Comment by Viincenttt** [comment]
Hi Fit2Page, 

The Klarna Pay methods aren't supported in the CreatePayment method. The Mollie API documentation states that it is only possible to create payments with Klarna Pay/Klarna Slice using the Order API. 

Unfortunatly, the Order API isn't supported yet, althought I have started working on it ( issue #79 ). I'm hoping to add support to the Order API at the end of december. 

Kind regards,
Vincent

**Comment by Viincenttt** [comment]
Support for this will be added when the Order API is ready.
