### ISSUE TITLE
Optional parameters

### ISSUE THREAD

**Issue by rajeevmishra2619** [Viincenttt/MollieApi#96]
Can any one tell me, how can I pass any extra property with value in the method- "CreatePaymentAsync".
I want to maintain the application state so I need a property which can maintain the application state while redirecting to payment screen.

**Comment by Viincenttt** [comment]
You could probably use the metadata property to store any extra values you require. For example:
PaymentRequest paymentRequest = new PaymentRequest();
paymentRequest.Metadata = "This is my data";
