### ISSUE TITLE
Mollie.Api.Client.MollieApiException: Not Found - Invalid resource endpoint  

### ISSUE THREAD

**Issue by dieterdp** [Viincenttt/MollieApi#97]
Hello

When i run the production version with live keys i get a Mollie.Api.Client.MollieApiException: Not Found - Invalid resource endpoint. But the money was taken from my account. So it works but i still get an exception back.

It works fine when using the test keys.

regards
Dieter

**Comment by Viincenttt** [comment]
Hi Dieterdp,

On what endpoint does this exception occur? 

Kind regards,
Vincent

**Comment by dieterdp** [comment]
Hi

This happens when i call GetPaymentAsync(),

regards
Dieter

**Comment by dieterdp** [comment]
any news on thi

> Hi Dieterdp,
> 
> On what endpoint does this exception occur?
> 
> Kind regards,
> Vincent

any news on this?

**Comment by Viincenttt** [comment]
Hi dieterdp,

I don't know why this error occurs. If the endpoint does work in test mode as you indicated, then I don't think it's an issue with the API. I recommend that you contact Mollie and send them a link to the endpoint you are trying to access. 

Let me know if/what their response is. 

Kind regards,
Vincent

**Comment by dieterdp** [comment]
Hello

I think i found something. It also happens when in testmode. When you stay on this screen for more then 20 seconds you get a Mollie.Api.Client.MollieApiException: Not Found - Invalid resource endpoint. 

regards
Dieter
 
![capture](https://user-images.githubusercontent.com/425205/51271165-1ac7d180-19c7-11e9-926f-a5301de40a7c.PNG)

**Comment by dieterdp** [comment]
problem solved, it was a session issue in ASP.NET Core
sorry for this

**Comment by Viincenttt** [comment]
Good to know!

**Comment by Martijnvos** [comment]
@dieterdp Would love to know how you fixed the session issue. I'm currently having the exact same problem.

**Comment by dieterdp** [comment]
I think my session time was to short, I changed it to

       services.AddSession(options =>
            {
                // Set a short timeout for easy testing.
                options.IdleTimeout = TimeSpan.FromSeconds(3600);
                options.Cookie.HttpOnly = true;
            });

**Comment by dieterdp** [comment]
i think my session time was to short and changed it to      
services.AddSession(options =>
            {
                // Set a short timeout for easy testing.
                options.IdleTimeout = TimeSpan.FromSeconds(3600);
                options.Cookie.HttpOnly = true;
            });

**Comment by Martijnvos** [comment]
Thanks! I'll give it a try
